- 3.4/graphs-pregel.md
- 3.5/graphs-pregel.md
Updated docs for new parameter for PREGEL_RESULT AQL function
> add information about withId parameter for PREGEL_RESULT function

- 3.5/release-notes-new-features35.md
add a note about transition to gtest
> added gtest to changelog

- 2.8/graphs.md
- 3.0/graphs.md
- 3.1/graphs.md
- 3.2/graphs.md
- 3.3/graphs.md
- 3.4/graphs.md
- 3.5/graphs.md
The above mentioned guarantees are not currently offered in AQL only graph module. (confirmed with @mchacki)
> Removed AQL

- _includes/program-option.html
- _includes/topnav.html
- js/site.js
- styles/gitbook/style.css
On mobile devices (<800px) we close the vertical navigation. We don't want it to play the closing animation (CSS transition).
> Improve sidebar hiding

- 2.8/documents.md
- 3.0/data-modeling-documents-document-address.md
- 3.0/getting-started-coming-from-sql.md
- 3.0/http/document-address-and-etag.md
- 3.1/data-modeling-documents-document-address.md
- 3.1/getting-started-coming-from-sql.md
- 3.1/http/document-address-and-etag.md
- 3.2/data-modeling-documents-document-address.md
- 3.2/getting-started-coming-from-sql.md
- 3.2/http/document-address-and-etag.md
- 3.3/data-modeling-documents-document-address.md
- 3.3/getting-started-coming-from-sql.md
- 3.3/http/document-address-and-etag.md
- 3.4/data-modeling-documents-document-address.md
- 3.4/getting-started-coming-from-sql.md
- 3.4/http/document-address-and-etag.md
- 3.5/data-modeling-documents-document-address.md
- 3.5/getting-started-coming-from-sql.md
- 3.5/http/document-address-and-etag.md
Non-valid JSON used for example documents, typo fixed
> Fix example doc JSON

- 3.4/administration-configuration.md
- 3.5/administration-configuration.md
> highlight the importance of placing one's comments at the beginning of

- 3.4/deployment-dc2-dc-cluster.md
- 3.5/deployment-dc2-dc-cluster.md
Extend unit file with nofiles setting (max number of open files)
> add nofiles limit

- 2.8/aql-examples.md
- 3.0/aql/examples-queries-no-collections.md
- 3.1/aql/examples-queries-no-collections.md
- 3.2/aql/examples-queries-no-collections.md
- 3.3/aql/examples-queries-no-collections.md
- 3.4/aql/examples-queries-no-collections.md
- 3.5/aql/examples-queries-no-collections.md
Examples not testable, see https://github.com/arangodb/docs/issues/75
> Fix/improve AQL examples "Queries without collections"

- 3.2/administration-configuration-rocks-db.md
- 3.3/administration-configuration-rocks-db.md
- 3.4/programs-arangod-rocksdb.md
- 3.5/programs-arangod-rocksdb.md
Hidden = not shown by the binary if you run `--help`
> Add version info for rocksdb.total-write-buffer-size, remove "Hidden" remark

- 3.5/architecture-deployment-modes-master-slave-architecture.md
- 3.5/release-notes-upgrading-changes35.md
Corresponds to this PR: https://github.com/arangodb/arangodb/pull/9366
> Bug fix/add shard id to replication client identifier

- 3.4/deployment-cloud-aws.md
- 3.5/deployment-cloud-aws.md
Please check the wording and if this is sufficient information
> Advice io1 storage / EC2 I3 instances for AWS

- 3.4/administration-starter-removal.md
- 3.5/administration-starter-removal.md
- ref:  https://github.com/arangodb/planning/issues/4152
> Added hint block for Starter Removal procedure

- 3.5/release-notes-upgrading-changes35.md
https://github.com/arangodb/arangodb/pull/9473
> Removed deprecation info

- 3.4/programs-arangod-temp.md
- 3.5/programs-arangod-temp.md
Documentation PR for the following change:
https://github.com/arangodb/arangodb/pull/9552
> Make it explicit that temp path and database directory should not overlap

- 3.4/aql/functions-document.md
- 3.5/aql/functions-document.md
Ref: https://github.com/arangodb/arangodb/issues/9568
> AQL MATCHES(): Add remarks about null and undefined

- 3.4/indexing-geo.md
- 3.5/indexing-geo.md
Document limitation raised in https://github.com/arangodb/arangodb/issues/9352.
> Add note about polygon limitation in GeoJSON functionality.

- 3.5/release-notes-new-features35.md
A few more links could be added, named indexes and index hints could be combined.
> Release Notes 3.5: Add some links to other chapters

- 3.5/arangosearch-views.md
> ArangoSearch primarySort is immutable

- 3.5/drivers/java-reference-collection-collection-manipulation.md
- 3.5/drivers/java-reference-graph.md
> Add minReplicationFactor docs for Java driver

- 3.4/installation-linux-ostuning-scripts.md
- 3.5/installation-linux-ostuning-scripts.md
- 3.6/installation-linux-ostuning-scripts.md
Added SUSE in OSTuning section
> Added SUSE in OSTuning section

- 3.5/programs-arangod-ssl.md
- 3.6/programs-arangod-ssl.md
https://github.com/arangodb/arangodb/pull/9817
https://github.com/arangodb/arangodb/pull/9818
To be updated in other places as well, e.g. driver documentation.
> Add TLS v1.3 as SSL protocol

- 3.4/aql/examples-grouping.md
- 3.4/aql/operations-collect.md
- 3.4/aql/operations-return.md
- 3.5/aql/examples-grouping.md
- 3.5/aql/operations-collect.md
- 3.5/aql/operations-return.md
- 3.6/aql/examples-grouping.md
- 3.6/aql/operations-collect.md
- 3.6/aql/operations-return.md
3.3 changed it from undefined order to not changing order of input
> RETURN DISTINCT does not change result order

- 3.5/programs-arangod-cluster.md
- 3.6/programs-arangod-cluster.md
https://github.com/arangodb/arangodb/pull/10111
> added documentation for sharding config startup parameters

- 3.6/aql/functions-string.md
Changed RANDOM_TOKEN block to reflect https://github.com/arangodb/arangodb/pull/10414
> Changed RANDOM_TOKEN block, now support 0 as value

- 3.6/programs-arangod-cluster.md
Documentation for devel/3.6 PR https://github.com/arangodb/arangodb/pull/10411
> added description for cluster upgrade option

- 3.6/release-notes-new-features36.md
This depends on merging https://github.com/arangodb/arangodb/pull/10459
> Release notes: more new features 3.6

- _includes/topnav.html
- _layouts/default.html
requested by Jan from marketing
Also remove download button pointing to website, as that page has nothing newer than 3.3 offline files and we are going to kill it.
> Change "Edit page" to "Contribute" with GitHub icon

- 3.6/release-notes-new-features36.md
More descriptions for parallel AQL
> add more descriptions for new AQL features

- 3.6/administration-engine-switch-engine.md
- 3.6/appendix-deprecated.md
- 3.6/architecture-storage-engines.md
- 3.6/getting-started-installation.md
- 3.6/programs-arangod-server.md
- 3.6/release-notes-new-features36.md
- 3.6/release-notes-upgrading-changes36.md
Some reformatting along the way
> Deprecate MMFiles storage engine

- 3.6/appendix-deprecated.md
- 3.6/programs-arangod-rocksdb.md
- 3.6/release-notes-new-features36.md
Add more MMFiles items to deprecated list.
> MMFiles engine: add more deprecation info

- 3.6/backup-restore.md
- 3.6/programs-arangobackup-examples.md
- 3.6/programs-arangobackup.md
- 3.6/release-notes-new-features36.md
Added --force option in a few more places and clarified lock behavior.
> HotBackup: added force option to docs

- 3.4/drivers/java-getting-started.md
- 3.5/drivers/java-getting-started.md
- 3.5/drivers/java-reference-setup.md
- 3.6/drivers/java-getting-started.md
- 3.6/drivers/java-reference-setup.md
https://github.com/arangodb/arangodb-java-driver/issues/304
> Java driver: Update supported versions text

- 3.4/deployment-kubernetes-deployment-resource.md
- 3.5/deployment-kubernetes-deployment-resource.md
- 3.6/deployment-kubernetes-deployment-resource.md
- 3.7/deployment-kubernetes-deployment-resource.md
add documentation for resource requirements in kube-arangodb
> Add docs for kube-arangodb 0.4.3 version

- 3.4/installation-linux-osconfiguration.md
- 3.5/installation-linux-osconfiguration.md
- 3.6/installation-linux-osconfiguration.md
- 3.7/installation-linux-osconfiguration.md
Know issues with NFS are performance and hard links required for Hot Backup.
> Added recommendation not to use NFS.

- 3.5/programs-arangodump-examples.md
- 3.5/programs-arangodump-maskings.md
- 3.6/programs-arangodump-examples.md
- 3.6/programs-arangodump-maskings.md
- 3.7/programs-arangodump-examples.md
- 3.7/programs-arangodump-maskings.md
https://github.com/arangodb/docs/issues/13
> Arangodump: Masking feature description improvements

- 3.5/security-auditing-audit-events.md
- 3.6/security-auditing-audit-events.md
- 3.7/security-auditing-audit-events.md
> Add audit log events for hotbackup to documentation.

- 3.7/generated/allComments.txt
- 3.7/generated/api-docs.json
- 3.7/http/administration-and-monitoring.md
https://github.com/arangodb/arangodb/pull/10977
https://deploy-preview-321--zealous-morse-14392b.netlify.com/docs/3.7/http/administration-and-monitoring.html#tls
> Add documentation for TLS cert rotation.

- _data/3.7-program-options-arangobackup.json
- _includes/program-option.html
- _plugins/ExtraFilters.rb
> Render new startup option info about os / component

- 3.7/release-notes-new-features37.md
https://github.com/arangodb/arangodb/pull/11030
> remove libcurl dependency

- 3.7/aql/fundamentals-data-types.md
- 3.7/highlights.md
- 3.7/release-notes-new-features37.md
> Incorporate release note changes into main docs

- 3.4/upgrading-starter.md
- 3.5/upgrading-starter.md
- 3.6/upgrading-starter.md
- 3.7/upgrading-starter.md
https://deploy-preview-341--zealous-morse-14392b.netlify.com/docs/3.7/upgrading-starter.html
> Starter deployment upgrading: pstree / KillMode=process

- 3.4/appendix-java-script-modules-console.md
- 3.4/aql/extending-conventions.md
- 3.4/aql/extending-functions.md
- 3.4/aql/extending.md
- 3.4/drivers/java-reference-graph-edges.md
- 3.4/troubleshooting-cluster-agency-dump.md
- 3.5/appendix-java-script-modules-console.md
- 3.5/aql/extending-conventions.md
- 3.5/aql/extending-functions.md
- 3.5/aql/extending.md
- 3.5/drivers/java-reference-graph-edges.md
- 3.5/troubleshooting-cluster-agency-dump.md
- 3.6/appendix-java-script-modules-console.md
- 3.6/aql/extending-conventions.md
- 3.6/aql/extending.md
- 3.6/drivers/java-reference-graph-edges.md
- 3.6/troubleshooting-cluster-agency-dump.md
- 3.7/appendix-java-script-modules-console.md
- 3.7/aql/extending-conventions.md
- 3.7/aql/extending.md
- 3.7/drivers/java-reference-graph-edges.md
- 3.7/troubleshooting-cluster-agency-dump.md
https://deploy-preview-343--zealous-morse-14392b.netlify.com/docs/3.6/appendix-java-script-modules-console.html
> Fixes 2020-02-19

- 3.7/aql/execution-and-performance-optimizer.md
- 3.7/release-notes-new-features37.md
This is short, but the Change is mostly internal, not much to document besides the explain of the rule (which was there)
Added New Features entry for it.
> Updates on Splice-Subqueries

- 3.4/programs-web-interface-aql-editor.md
- 3.5/programs-web-interface-aql-editor.md
- 3.6/programs-web-interface-aql-editor.md
- 3.7/programs-web-interface-aql-editor.md
https://github.com/arangodb/arangodb/issues/10451
> Web UI shortcuts: Add execute selection, format as table

- 3.7/release-notes-api-changes37.md
added api gharial changes due new feature: Satellite Graphs
> REST API changes satellite graphs

- 3.5/aql/functions-arangosearch.md
- 3.6/aql/functions-arangosearch.md
- 3.6/aql/functions-string.md
- 3.7/aql/functions-arangosearch.md
- 3.7/aql/functions-string.md
Added description for NGRAM_MATCH, NGRAM_SIMILARITY and NGRAM_POSITIONAL_SIMILARITY functions
> Added ngram similarity functions description

- 3.4/drivers/js-getting-started.md
- 3.5/drivers/js-getting-started.md
- 3.6/drivers/js-getting-started.md
- 3.7/drivers/js-getting-started.md
Remove mentions of concrete versions.
@pluma Is the statement about IE11 still correct?
> ArangoJS: Node.js support

- 3.7/installation-compiling-debian.md
- 3.7/installation-compiling-windows.md
- 3.7/release-notes-new-features37.md
Accompanying docs PR for https://github.com/arangodb/arangodb/pull/11308
> added note about RocksDB upgrade

- 3.7/aql/functions-arangosearch.md
- 3.7/aql/functions-string.md
Added important note for analyzers to be used with NGRAM_MATCH  and PHRASE functions
> Add remark about required Analyzer features for PHRASE() & NGRAM_MATCH()

- 3.7/aql/functions-arangosearch.md
Supported IN_RANGE() in PHRASE().
> phrase in_range

- 3.4/aql/operations-insert.md
- 3.4/aql/operations-replace.md
- 3.4/aql/operations-update.md
- 3.4/aql/operations-upsert.md
- 3.5/aql/operations-insert.md
- 3.5/aql/operations-replace.md
- 3.5/aql/operations-update.md
- 3.5/aql/operations-upsert.md
- 3.6/aql/operations-insert.md
- 3.6/aql/operations-replace.md
- 3.6/aql/operations-update.md
- 3.6/aql/operations-upsert.md
- 3.7/aql/operations-insert.md
- 3.7/aql/operations-replace.md
- 3.7/aql/operations-update.md
- 3.7/aql/operations-upsert.md
- 3.7/data-modeling-documents-document-methods.md
- 3.7/release-notes-api-changes37.md
docs PR for https://github.com/arangodb/arangodb/pull/11379
> add overwrite mode docs

- 3.7/aql/functions-arangosearch.md
- 3.7/aql/functions-array.md
- 3.7/aql/functions-miscellaneous.md
- 3.7/aql/functions-string.md
- 3.7/aql/graphs-traversals.md
- 3.7/aql/operations-search.md
- 3.7/arangosearch-analyzers.md
- 3.7/arangosearch-views.md
- 3.7/data-modeling-documents-document-methods.md
- 3.7/data-modeling-documents-schema-validation.md
- 3.7/release-notes-new-features37.md
STARTS_WITH supports an array of prefixes with minimum match count.
> starts_with with an array of prefixes

- 3.7/programs-arangod-env-vars.md
- 3.7/programs-arangod-rocksdb.md
- 3.7/release-notes-new-features37.md
- 3.7/release-notes-upgrading-changes37.md
Companion PR to https://github.com/arangodb/arangodb/pull/11485
> RocksDB total write buffer / block cache size: lower default values for small systems

- 3.3/appendix-java-script-modules-crypto.md
- 3.4/appendix-java-script-modules-crypto.md
- 3.5/appendix-java-script-modules-crypto.md
- 3.6/appendix-java-script-modules-crypto.md
- 3.7/appendix-java-script-modules-crypto.md
https://github.com/arangodb/arangodb/issues/2597
Open questions:
- how does checkAndMarkNonce() work?
- are nonces stored in memory (volatile)?
- do nonces have an expiration period?
> Improve crypto.createNonce(), .checkAndMarkNonce()

- 3.4/views-arango-search-getting-started.md
- 3.5/aql/operations-search.md
- 3.5/arangosearch-examples.md
- 3.6/aql/operations-search.md
- 3.6/arangosearch-examples.md
- 3.7/aql/operations-search.md
- 3.7/arangosearch-examples.md
> ArangoSearch example fix

- 3.4/administration-cluster.md
- 3.5/administration-cluster.md
- 3.6/administration-cluster.md
- 3.7/administration-cluster.md
> Cluster admin: replicationFactor and DB-Server count

- 3.7/aql/execution-and-performance-optimizer.md
- 3.7/release-notes-new-features37.md
Docs PR for https://github.com/arangodb/arangodb/pull/11542
> added docs for "optimize-count" optimizer rule

- 3.5/aql/invocation-with-arangosh.md
- 3.6/release-notes-new-features36.md
- 3.7/release-notes-new-features36.md
Wait for v3.5.4 / upstream PR to be merged:
https://github.com/arangodb/arangodb/pull/10405/files
> Backport query timeout feature to v3.5.4

- 3.6/release-notes-upgrading-changes36.md
- 3.7/release-notes-upgrading-changes36.md
- 3.7/release-notes-upgrading-changes37.md
Docs PR for https://github.com/arangodb/arangodb/pull/11694
> don't exclude requests to `/_admin/aardvark` from request statistics.

- 3.4/drivers/spark-connector-reference-java.md
- 3.4/drivers/spark-connector-reference-scala.md
- 3.5/drivers/spark-connector-reference-java.md
- 3.5/drivers/spark-connector-reference-scala.md
- 3.6/drivers/spark-connector-reference-java.md
- 3.6/drivers/spark-connector-reference-scala.md
- 3.7/drivers/spark-connector-reference-java.md
- 3.7/drivers/spark-connector-reference-scala.md
Added doc related to https://github.com/arangodb/arangodb-spark-connector/pull/21
> added spark write method options

- 3.7/release-notes-upgrading-changes37.md
Documentation for https://github.com/arangodb/arangodb/pull/11742
> arangodump/restore: warn (fail) if (all) collections are missing

- 3.7/programs-arangod-env-vars.md
- 3.7/release-notes-new-features37.md
- 3.7/troubleshooting-arangod.md
Documentation PR for https://github.com/arangodb/arangodb/pull/11684
> update docs for crash handler v2

- 3.5/programs-arangoimport-details.md
- 3.6/programs-arangoimport-details.md
- 3.7/programs-arangoimport-details.md
https://github.com/arangodb/arangodb/issues/11765
> Arangoimport: Only UTF-8 without BOM is supported

- 3.5/aql/invocation-with-arangosh.md
- 3.6/aql/invocation-with-arangosh.md
- 3.7/aql/invocation-with-arangosh.md
_olivierb in community slack:_
Missing the fullCount option in the doc here https://www.arangodb.com/docs/stable/aql/invocation-with-arangosh.html#setting-options
Added the missing options based on https://www.arangodb.com/docs/stable/http/aql-query-cursor-accessing-cursors.html
> Add missing arangosh options

- 3.7/highlights.md
~TODO: link to parallel traversal content once it's there~
It's EE only, added in #465 to the EE section
> Update 3.7 Highlights

- 3.7/data-modeling-documents-schema-validation.md
- 3.7/release-notes-new-features37.md
- 3.8/data-modeling-documents-schema-validation.md
- 3.8/release-notes-new-features37.md
Update docs for schema validation after test
> fix schema validation examples

- 3.7/release-notes-new-features37.md
- 3.8/release-notes-new-features37.md
docs PR for https://github.com/arangodb/arangodb/pull/11935
> remove replication changes from the docs for now

- 3.6/generated/arangod-options.json
- 3.6/programs-arangod-transaction.md
- 3.7/generated/arangod-options.json
- 3.7/programs-arangod-transaction.md
- 3.8/generated/arangod-options.json
- 3.8/programs-arangod-transaction.md
- _data/3.6-manual.yml
- _data/3.7-manual.yml
- _data/3.8-manual.yml
Upstream PRs
https://github.com/arangodb/arangodb/pull/11854
https://github.com/arangodb/arangodb/pull/12042
https://github.com/arangodb/arangodb/pull/11994
> Add arangod transaction startup option category

- 3.8/data-modeling-databases-working-with.md
- 3.8/release-notes-api-changes38.md
Docs PR for https://github.com/arangodb/arangodb/pull/12133
> make engine stats work in cluster

- 3.7/release-notes-api-changes37.md
- 3.7/release-notes-upgrading-changes37.md
- 3.7/security-security-options.md
- 3.8/release-notes-api-changes37.md
- 3.8/release-notes-upgrading-changes37.md
- 3.8/security-security-options.md
documentation for https://github.com/arangodb/arangodb/pull/12101
> documentation for numberOfServers hardening

- 3.3/administration-encryption.md
- 3.4/security-encryption.md
- 3.5/security-encryption.md
- 3.6/security-encryption.md
- 3.7/release-notes-new-features37.md
- 3.7/security-encryption.md
- 3.8/release-notes-new-features37.md
- 3.8/security-encryption.md
docs PR for https://github.com/arangodb/enterprise/pull/522
> added documentation for encryption key rotation API toggle

- 3.7/release-notes-api-changes37.md
- 3.7/release-notes-upgrading-changes37.md
- 3.8/release-notes-api-changes37.md
Document API change for error message string.
> document return value change

- 3.8/release-notes-api-changes38.md
- 3.8/release-notes-upgrading-changes38.md
Docs PR for https://github.com/arangodb/arangodb/pull/12189
> remove plan version

- 3.4/programs-arangod-log.md
- 3.5/programs-arangod-log.md
- 3.6/programs-arangod-log.md
- 3.6/programs-arangod-transaction.md
- 3.6/release-notes-upgrading-changes36.md
- 3.7/aql/functions-numeric.md
- 3.7/aql/functions-string.md
- 3.7/aql/functions-type-cast.md
- 3.7/programs-arangod-log.md
- 3.7/programs-arangod-transaction.md
- 3.7/release-notes-new-features37.md
- 3.7/release-notes-upgrading-changes36.md
- 3.8/aql/functions-numeric.md
- 3.8/aql/functions-string.md
- 3.8/aql/functions-type-cast.md
- 3.8/programs-arangod-log.md
- 3.8/programs-arangod-transaction.md
- 3.8/release-notes-upgrading-changes36.md
Docs PR for PRs
* 3.7: https://github.com/arangodb/arangodb/pull/12360
* devel: https://github.com/arangodb/arangodb/pull/11790
> add docs for IPV4 AQL functions and PRODUCT AQL function

- 3.4/drivers/spring-data-getting-started.md
- 3.4/drivers/spring-data-reference-mapping-auditing.md
- 3.4/drivers/spring-data-reference-mapping-converter.md
- 3.4/drivers/spring-data-reference-mapping-events.md
- 3.4/drivers/spring-data-reference-mapping.md
- 3.7/drivers/spring-data-getting-started.md
- 3.7/drivers/spring-data-reference-mapping-auditing.md
- 3.7/drivers/spring-data-reference-mapping-events.md
- 3.7/drivers/spring-data-reference-mapping.md
replaced deprecated AbstractArangoConfiguration with ArangoConfiguration
> Spring Data configuration update

- 3.7/http/administration-and-monitoring-metrics.md
- 3.7/release-notes-new-features37.md
- 3.8/http/administration-and-monitoring-metrics.md
Docs PR for https://github.com/arangodb/arangodb/pull/12560 and https://github.com/arangodb/arangodb/pull/12561
> add V8 usage metrics

- 3.8/http/administration-and-monitoring-metrics.md
- 3.8/release-notes-new-features38.md
Docs PR for https://github.com/arangodb/arangodb/pull/12539
> add disk usage metrics to docs

- 3.7/http/administration-and-monitoring-metrics.md
- 3.8/http/administration-and-monitoring-metrics.md
- 3.8/release-notes-new-features38.md
https://github.com/arangodb/arangodb/pull/12554
> add more replication metrics

- 3.7/programs-arangod-rocksdb.md
- 3.8/programs-arangod-rocksdb.md
https://github.com/arangodb/arangodb/pull/12591
https://github.com/arangodb/arangodb/pull/12590
> Document --rocksdb.max-write-buffer-size-to-maintain

- 3.8/arangosearch.md
- styles/site.css
https://deploy-preview-554--zealous-morse-14392b.netlify.app/docs/3.8/arangosearch.html
> Add facility for lead paragraphs

- 3.4/drivers/index.md
- 3.7/drivers/index.md
added community C++ developed library tash (https://gitlab.com/neel.basu/tash)
> - added tash

- 3.4/drivers/index.md
- 3.7/drivers/index.md
- scripts/fetchRefs.sh
We might want to add a few more resources, @MrPieces ?
> Add "Community resources" to Drivers homepage

- 3.7/arangosearch-analyzers.md
- 3.8/arangosearch-analyzers.md
- 3.8/generated/Examples/analyzerPipelineDelimiterStem.generated
- 3.8/generated/Examples/analyzerPipelineNgramUpper.generated
- 3.8/generated/Examples/analyzerPipelineUpperNgram.generated
- 3.8/generated/Examples/analyzerTextEdgeNgram.generated
- 3.8/generated/Examples/analyzerTextNoStem.generated
- 3.8/generated/Examples/analyzerTextStem.generated
- 3.8/generated/allComments.txt
- 3.8/highlights.md
- 3.8/release-notes-new-features38.md
- styles/website.css
Added description for new analyzer type "pipeline"
> added pipeline analyzer description

- 3.6/programs-arangod-query.md
- 3.7/programs-arangod-query.md
- 3.8/programs-arangod-query.md
https://github.com/arangodb/arangodb/pull/12640
https://github.com/arangodb/arangodb/pull/12639
https://github.com/arangodb/arangodb/pull/12637
> New --query.max-runtime startup option

- 3.8/http/administration-and-monitoring-metrics.md
- 3.8/release-notes-new-features38.md
https://github.com/arangodb/arangodb/pull/12663
> Add new RocksDB inodes & replication metrics

- 3.8/appendix-deprecated.md
- 3.8/programs-arangod-database.md
- 3.8/programs-arangod-ttl.md
- 3.8/release-notes-upgrading-changes38.md
Docs PR for https://github.com/arangodb/arangodb/pull/12914
> obsolete some unused MMFiles options

- 3.7/http/administration-and-monitoring-metrics.md
- 3.8/http/administration-and-monitoring-metrics.md
- 3.8/release-notes-new-features38.md
Documentation PR for https://github.com/arangodb/arangodb/pull/12987
> docs for locking instrumentation

- 3.6/architecture-deployment-modes-cluster-architecture.md
- 3.7/architecture-deployment-modes-cluster-architecture.md
- 3.8/architecture-deployment-modes-cluster-architecture.md
Add extra "Limitations" section for OneShard feature
> mention restrictions for OneShard optimization

- 3.8/arangosearch-analyzers.md
- 3.8/generated/Examples/analyzerAqlCollapse.generated
- 3.8/generated/Examples/analyzerAqlConcat.generated
- 3.8/generated/Examples/analyzerAqlFilter.generated
- 3.8/generated/Examples/analyzerAqlFilterNull.generated
- 3.8/generated/Examples/analyzerAqlSoundex.generated
- 3.8/highlights.md
- 3.8/release-notes-new-features38.md
Added description for new analyzer type "aql"
> added aql analyzer description

- 3.8/release-notes-api-changes38.md
- 3.8/release-notes-upgrading-changes38.md
https://github.com/arangodb/arangodb/pull/13172
> stringify Pregel execution numbers

- 3.8/data-modeling-collections-collection-methods.md
- 3.8/release-notes-new-features38.md
https://github.com/arangodb/arangodb/pull/13195
> Cluster support for collection.checksum() method

- 3.3/aql/tutorial-crud.md
- 3.4/aql/tutorial-crud.md
- 3.5/aql/tutorial-crud.md
- 3.6/aql/tutorial-crud.md
- 3.7/aql/tutorial-crud.md
- 3.8/aql/tutorial-crud.md
Fixes https://github.com/arangodb/arangodb/issues/13296
> Fix typo in tutorial-crud.md

- 3.5/aql/operations-search.md
- 3.6/aql/operations-search.md
- 3.7/aql/operations-search.md
- 3.8/aql/operations-search.md
as pointed out by  @xsansha in https://github.com/arangodb/docs/issues/604
> fix indentation

- 3.8/programs-arangodump-examples.md
- 3.8/release-notes-new-features38.md
docs PR for https://github.com/arangodb/arangodb/pull/13404
> arangodump: Shard-parallelism and smaller dumps

- 3.3/graphs-pregel.md
- 3.4/graphs-pregel.md
- 3.5/graphs-pregel.md
- 3.6/graphs-pregel.md
- 3.7/graphs-pregel.md
- 3.8/graphs-pregel.md
Needs sharding guarantees of SmartGraphs so that the outgoing edges are placed on the same DB-Server as the vertex.
Preview: https://deploy-preview-609--zealous-morse-14392b.netlify.app/docs/3.8/graphs-pregel.html#prerequisites
> Pregel: Collection sharding in cluster

- 3.7/aql/operations-search.md
- 3.8/aql/operations-search.md
- 3.8/release-notes-new-features38.md
Adds description of new 'countApproximate' option for ArangoSearch Views
> add 'countApproximate' option description

- 3.8/programs-arangod-ldap.md
Added placeholder {USER} for ldap.search-filter
> added placeholder for ldap.search-filter

- 3.7/programs-arangod-ldap.md
backport of https://github.com/arangodb/docs/pull/611
> added {USER} replacement

- 3.8/release-notes-api-changes38.md
- 3.8/release-notes-upgrading-changes38.md
Docs PR for https://github.com/arangodb/arangodb/pull/13206
> Change file descriptors threshold handling at startup

- 3.8/http/administration-and-monitoring.md
- 3.8/release-notes-api-changes38.md
Docs PR for https://github.com/arangodb/arangodb/pull/13504
> more improvements for logging

- 3.7/programs-arangod-audit.md
- 3.7/programs-arangod-log.md
- 3.8/programs-arangod-audit.md
- 3.8/programs-arangod-log.md
- 3.8/release-notes-new-features38.md
https://github.com/arangodb/arangodb/pull/13492
> improvements for logging

- 3.8/programs-arangod-log.md
- 3.8/release-notes-new-features38.md
Docs PR for hostname logging
https://github.com/arangodb/arangodb/pull/13630
> docs PR for hostname logging

- 3.8/programs-arangod-query.md
- 3.8/release-notes-new-features38.md
- 3.8/release-notes-upgrading-changes38.md
Documentation updates for `--query.global-memory-limit` and `--query.memory-limit-override`.
> docs PR for memory limit changes

- 3.8/programs-arangod-env-vars.md
https://github.com/arangodb/arangodb/pull/13706
> Allow setting path to the timezone information via the `TZ_DATA` environment variable

- 3.8/indexing-working-with-indexes.md
- 3.8/release-notes-api-changes38.md
- 3.8/release-notes-new-features38.md
Some accompanying docublocks changes are in https://github.com/arangodb/arangodb/pull/13723
> update docs w.r.t. index selectivity estimates

- 3.8/release-notes-new-features38.md
Requires the following PRs to be merged:
* https://github.com/arangodb/arangodb/pull/13674
* https://github.com/arangodb/arangodb/pull/13662
> Web UI improvements & arangoexport --documents-per-batch 3.8 release notes

- 3.8/highlights.md
- 3.8/release-notes-new-features38.md
- 3.8/security-encryption.md
Add hardware-acceleration for encryption at rest to feature list.
> add hardware-acceleration for encryption at rest

- 3.7/programs-arangod-audit.md
- 3.7/programs-arangod-log.md
https://github.com/arangodb/arangodb/pull/13755
> allow dynamic logfile names for testing

- 3.8/architecture-deployment-modes-cluster-architecture.md
- 3.8/http/transaction-stream-transaction.md
- 3.8/programs-arangobackup-examples.md
- 3.8/programs-arangod-transaction.md
- 3.8/release-notes-upgrading-changes38.md
Docs PR for https://github.com/arangodb/arangodb/pull/13731
> changes for streaming transactions improvements PR

- 3.8/release-notes-new-features38.md
- 3.8/security-security-options.md
Add new shard synchronization protocol to 3.8 release notes, as it was missing before.
> add new shard synchronization protocol

- 3.8/release-notes-api-changes38.md
- 3.8/release-notes-new-features38.md
- 3.8/release-notes-upgrading-changes38.md
Adjust release notes for metrics for 3.8.
> New features 3.8 w.r.t. metrics

- 3.8/programs-arangod-cluster.md
- 3.8/release-notes-new-features38.md
Please **do not merge** yet.
I will check with others if they have some performance improvements they would like to add to this.
> started docs on performance improvements

- 3.8/release-notes-new-features38.md
- 3.8/release-notes-upgrading-changes38.md
Docs PR for https://github.com/arangodb/arangodb/pull/13816
> Added an option to lock down /_admin/cluster

- 3.7/drivers/index.md
- updated erlArango url
- added eArango
> erlArango updates

- 3.8/programs-arangoimport-examples-csv.md
https://github.com/arangodb/arangodb/pull/13900
> Add --headers-file option to arangoimport

- 3.8/aql/common-errors.md
- 3.8/programs-arangod-query.md
- 3.8/release-notes-new-features38.md
https://github.com/arangodb/arangodb/pull/13872
> Added option to disallow usage of collections in expression

- 3.8/arangosearch-analyzers.md
adds descriptions for new Aql analyzer parameter
https://github.com/arangodb/arangodb/pull/13894
> add returnType description for AQL analyzer

- 3.9/generated/arangovpack-options.json
- 3.9/programs-arangovpack-options.md
- 3.9/programs-arangovpack.md
- 3.9/programs.md
- 3.9/release-notes-new-features39.md
- README.md
- _data/3.9-manual.yml
- _data/3.9-program-options-arangovpack.json
https://github.com/arangodb/arangodb/commit/ec45ca885482d670bc25cc58223c848837c31b7b
> Add arangovpack to programs

- 3.8/appendix-deprecated.md
- 3.8/release-notes-api-changes38.md
- 3.9/appendix-deprecated.md
- 3.9/release-notes-upgrading-changes39.md
https://github.com/arangodb/arangodb/pull/13997
> deprecate the /_admin/statistics API in favor of /_admin/metrics/v2

- 3.7/http/aql-query-cursor-accessing-cursors.md
- 3.8/http/aql-query-cursor-accessing-cursors.md
- 3.8/http/aql-query-cursor-query-results.md
- 3.8/release-notes-api-changes38.md
- 3.9/appendix-deprecated.md
- 3.9/http/aql-query-cursor-accessing-cursors.md
- 3.9/http/aql-query-cursor-query-results.md
https://github.com/arangodb/arangodb/pull/14004
> Add endpoint `POST /_api/cursor/<cursor-id>`

- 3.6/programs-arangoexport-examples.md
- 3.7/programs-arangoexport-examples.md
- 3.8/programs-arangoexport-examples.md
- 3.8/release-notes-new-features38.md
- 3.9/programs-arangoexport-examples.md
https://github.com/arangodb/arangodb/pull/14041
> Added --query-max-runtime option for arangoexport

- 3.8/programs-arangorestore-examples.md
- 3.8/programs-arangorestore-fast-cluster-restore.md
- 3.8/release-notes-new-features38.md
- 3.8/release-notes-upgrading-changes38.md
- 3.9/programs-arangorestore-examples.md
- 3.9/programs-arangorestore-fast-cluster-restore.md
- 3.9/release-notes-upgrading-changes39.md
https://github.com/arangodb/arangodb/pull/14010
> improve parallelism capabilities of arangorestore

- 3.6/aql/functions-miscellaneous.md
- 3.7/aql/functions-miscellaneous.md
- 3.8/aql/functions-miscellaneous.md
- 3.9/aql/functions-miscellaneous.md
Align documentation for NOT_NULL, FIRST_LIST and FIRST_DOCUMENT
> Align documentation sections

- 3.9/release-notes-new-features39.md
see https://github.com/arangodb/arangodb/pull/14185
> added redirect options

- 3.8/aql/operations-window.md
- 3.8/generated/Examples/windowAggregationRangeDuration.generated
- 3.8/generated/Examples/windowAggregationRangeValue.generated
- 3.8/generated/Examples/windowAggregationRow.generated
- 3.8/generated/Examples/windowAggregationRowGrouped.generated
- 3.9/aql/operations-window.md
- 3.9/generated/Examples/windowAggregationRangeDuration.generated
- 3.9/generated/Examples/windowAggregationRangeValue.generated
- 3.9/generated/Examples/windowAggregationRow.generated
- 3.9/generated/Examples/windowAggregationRowGrouped.generated
Some minor clarifications regarding the new WINDOW operation.
> WINDOW operation clarifications

- 3.8/analyzers.md
- 3.8/highlights.md
- 3.8/release-notes-new-features38.md
- 3.9/analyzers.md
- 3.9/highlights.md
add hex parameter for stopwords analyzer
> fix stopwords description

- 3.6/backup-restore.md
- 3.6/programs-arangobackup-examples.md
- 3.7/backup-restore.md
- 3.7/deployment-kubernetes-backup-resource.md
- 3.7/programs-arangobackup-examples.md
- 3.8/backup-restore.md
- 3.8/programs-arangobackup-examples.md
- 3.9/backup-restore.md
- 3.9/programs-arangobackup-examples.md
As a consequence of solving https://arangodb.atlassian.net/browse/PRESUPP-349 adding a troubleshooting hint. Last paragraph on the rclone configuration section. I have attached here a screenshot of the section for easy review
> hint to examine rclone configuration using standalone binary

- 3.9/release-notes-api-changes39.md
- 3.9/release-notes-upgrading-changes39.md
https://github.com/arangodb/arangodb/pull/14425
> Removed redirects for some cluster rest handler

- 3.7/arangosearch-fuzzy-search.md
- 3.7/arangosearch.md
- 3.8/arangosearch-fuzzy-search.md
- 3.8/arangosearch.md
- 3.9/arangosearch-fuzzy-search.md
- 3.9/arangosearch.md
- _data/3.7-manual.yml
- _data/3.8-manual.yml
- _data/3.9-manual.yml
Based on Lunch Break video
https://deploy-preview-717--zealous-morse-14392b.netlify.app/docs/3.7/arangosearch-fuzzy-search.html
> Add fuzzy search examples

- 3.9/aql/functions-numeric.md
- 3.9/release-notes-new-features39.md
https://github.com/arangodb/arangodb/pull/14364
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-decay
> added info about new decay functions

- 3.9/programs-arangod-general.md
- 3.9/release-notes-new-features39.md
https://github.com/arangodb/arangodb/pull/14383
> Add new command line-option --version-json

- 3.6/foxx-guides-auth.md
- 3.7/foxx-guides-auth.md
- 3.8/foxx-guides-auth.md
- 3.9/foxx-guides-auth.md
In the example above the authentication result is stored in the password field.
> fix login example

- 3.9/aql/functions-numeric.md
- 3.9/release-notes-new-features39.md
https://github.com/arangodb/arangodb/pull/14555
> AQL distance function

- 3.9/programs-arangod-server.md
- 3.9/release-notes-upgrading-changes39.md
https://github.com/arangodb/arangodb/pull/14118
> Revive startup parameter `--server.session-timeout`

- 3.9/release-notes-api-changes39.md
- 3.9/release-notes-new-features39.md
- 3.9/security-security-options.md
https://github.com/arangodb/arangodb/pull/14639
> Improve supportability

- 3.7/administration-configuration.md
- 3.8/administration-configuration.md
- 3.9/administration-configuration.md
- 3.9/release-notes-api-changes39.md
- 3.9/release-notes-new-features39.md
https://github.com/arangodb/arangodb/pull/14677
> Add pseudo log topic "all" (APM-120)

- 3.9/release-notes-upgrading-changes39.md
https://github.com/arangodb/arangodb/pull/14749
> Fix cluster-internal network protocol to HTTP/1

- 3.9/appendix-deprecated.md
Add more details to deprecations section.
> more deprecations

- 3.7/data-modeling-collections-database-methods.md
- 3.8/data-modeling-collections-database-methods.md
- 3.9/data-modeling-collections-database-methods.md
> Change term vocbase to database

- 3.9/aql/graphs-traversals.md
- 3.9/release-notes-new-features39.md
Documentation for https://github.com/arangodb/arangodb/pull/14748
> APM-70: PRUNE with output variable

- 3.9/programs-arangoimport-examples-csv.md
- 3.9/release-notes-new-features39.md
https://github.com/arangodb/arangodb/pull/14761
> Add `--datatype` option to arangoimport

- drivers/spring-data-reference-repositories-queries-query-methods.md
doc for https://github.com/arangodb/spring-data/pull/221
> SPEL support

- 3.9/aql/operations-upsert.md
- 3.9/release-notes-new-features39.md
Documentation for https://github.com/arangodb/arangodb/pull/14817
> Added documentation for APM-121

- 3.9/programs-arangod-log.md
- 3.9/release-notes-new-features39.md
Documentation for https://github.com/arangodb/arangodb/pull/14805
> Added documentation for feature/escaping-unicode-control-chars

- drivers/index.md
Test change to documentation - adding some minimal words of explanation.
> Add introduction to drivers

- 3.7/aql/functions-string.md
> Revert "Add examples for AQL string functions"

- 3.10/aql/operations-collect.md
- 3.7/aql/operations-collect.md
- 3.8/aql/operations-collect.md
- 3.9/aql/operations-collect.md
It works with more than arrays!
> Better introduction for COLLECT

- 3.10/programs-arangobench.md
- 3.10/release-notes-new-features310.md
- 3.9/programs-arangobench.md
- 3.9/release-notes-new-features39.md
Documentation for https://github.com/arangodb/arangodb/pull/15067 and backport for 3.9
> Added documentation for APM-209

- 3.9/release-notes-api-changes39.md
> removed a superfluous headline

- 3.10/release-notes-new-features310.md
- 3.9/release-notes-new-features39.md
Docs PR for 
* immer library upgrade: https://github.com/arangodb/arangodb/pull/15072
* boost library upgrade: https://github.com/arangodb/arangodb/pull/15139
* rocksdb library upgrade: https://github.com/arangodb/arangodb/pull/15186
> mention several version upgrades

- 3.10/aql/invocation-with-arangosh.md
- 3.9/aql/invocation-with-arangosh.md
- 3.9/release-notes-api-changes39.md
- 3.9/release-notes-new-features39.md
Docs PR for:
* devel: https://github.com/arangodb/arangodb/pull/15244
* 3.9: https://github.com/arangodb/arangodb/pull/15245
> clarify meaning of `maxNodesPerCallStack` attribute

- 3.10/deployment-production-checklist.md
- 3.7/deployment-production-checklist.md
- 3.8/deployment-production-checklist.md
- 3.9/deployment-production-checklist.md
Fix links and terminology, as well as apply formatting conventions to the memory considerations section added by #835.
> Follow-up on production checklist PR

- 3.10/programs-arangoexport-examples.md
- 3.8/programs-arangoexport-examples.md
- 3.9/programs-arangoexport-examples.md
Documentation for https://github.com/arangodb/arangodb/pull/15277
> [APM-256]: escape potential formulae in arangoexport CSV results

- 3.10/programs-arangobench-options.md
- 3.10/programs-arangobench.md
- 3.10/release-notes-upgrading-changes310.md
Documentation for https://github.com/arangodb/arangodb/pull/15236
> Added documentation for PR 15236

- 3.10/programs-arangoexport-examples.md
- 3.10/release-notes-new-features310.md
- 3.10/release-notes-upgrading-changes310.md
Documentation for https://github.com/arangodb/arangodb/pull/15324
> Added documentation for new flag  in arangoexport

- 3.10/release-notes-upgrading-changes310.md
Upgrading notes for https://github.com/arangodb/arangodb/pull/15354
> Update upgrading nodes about db._version change.

- 3.10/programs-arangod-rocksdb.md
- 3.8/programs-arangod-rocksdb.md
- 3.9/programs-arangod-rocksdb.md
docs PR for https://github.com/arangodb/arangodb/pull/15317
> added various startup options for throttle configuration

- 3.10/security-security-options.md
- 3.9/release-notes-api-changes39.md
- 3.9/security-security-options.md
Docs PR for https://github.com/arangodb/arangodb/pull/15459 and https://github.com/arangodb/arangodb/pull/15460
> BTS-707: more support-info permissions more sensible

- 3.9/release-notes-new-features39.md
Adds examples of how two new optimizations can be observed in the query explain output as requested in https://arangodb.atlassian.net/browse/BTS-719
> BTS-719 | Query explain output for 3.9 traversal optimizations

- 3.10/administration-active-failover.md
- oasis/oasisctl-completion.md
Upstream fix: https://github.com/arangodb-managed/oasisctl/pull/121
> Temporary fix for oasisctl completion Markdown rendering issues

- 3.10/aql/execution-and-performance-query-profiler.md
- 3.10/release-notes-new-features310.md
Docs PR for https://github.com/arangodb/arangodb/pull/15637
> Add "Filtered" column to query profiling output

- 3.9/administration-license.md
clearify update process for licenses
> clearify updates

- 3.10/release-notes-api-changes310.md
* About remove v1 metrics
* About change metrics output
> Metrics API changes

- 3.10/data-modeling-graphs-from-rdf.md
- 3.7/data-modeling-graphs-from-rdf.md
- 3.8/data-modeling-graphs-from-rdf.md
- 3.9/data-modeling-graphs-from-rdf.md
URL link change for the RDF example notebook.
> updates rdf link to interactive_tutorials repo

- _data/3.7-drivers.yml
- drivers/spark-connector-new.md
Renamed Spark Datasource according to Apache naming guidelines.
> renamed Spark Datasource

- 3.10/aql/fundamentals-limitations.md
- 3.10/release-notes-upgrading-changes310.md
Documentation PR for https://github.com/arangodb/arangodb/pull/15794
> Limit max recursion depth

- drivers/index.md
- added ArangoDB Datasource for Apache Spark to the drivers list
- updated the url of python-arango
> Added Spark Datasource to drivers list

- 3.7/architecture-deployment-modes-dc2-dc-limitations.md
Document version limitations for DC2DC.
> Document version limitations for DC2Dc

- 3.10/release-notes-api-changes310.md
- 3.10/release-notes-new-features310.md
Documentation for https://github.com/arangodb/arangodb/pull/15909.
> Added documentation for optimizer-rules-getter

- 3.10/programs-arangod-general.md
- 3.3/administration-configuration-general-arangod.md
- 3.4/programs-arangod-global.md
- 3.5/programs-arangod-global.md
- 3.6/programs-arangod-general.md
- 3.7/programs-arangod-general.md
- 3.8/programs-arangod-general.md
- 3.9/programs-arangod-general.md
- 3.9/release-notes-new-features39.md
Added documentation to icu-language option
> icu-language option

- 3.10/release-notes-new-features310.md
Mention recent zlib library upgrade
> mention zlib library upgrade

- 3.10/programs-arangod-rocksdb.md
- 3.9/programs-arangod-rocksdb.md
https://github.com/arangodb/arangodb/pull/16118
> Make transaction lock stripes configurable

- 3.10/release-notes-new-features310.md
- 3.10/release-notes-upgrading-changes310.md
- https://github.com/arangodb/arangodb/pull/15324
- https://github.com/arangodb/arangodb/pull/16100
- https://github.com/arangodb/arangodb/pull/13433
- https://github.com/arangodb/arangodb/pull/14893
> add features missing in the 3.10 release notes

- 3.10/indexing.md
- 3.7/indexing.md
- 3.8/indexing.md
- 3.9/indexing.md
- The ArangoSearch section isn't mentioned on the indexing page but I think it should be since it lives there now.
> adds arangosearch mention to indexes page

- 3.10/release-notes-new-features310.md
Docs PR for https://github.com/arangodb/arangodb/pull/16227
> mention RocksDB version upgrade

- 3.10/analyzers.md
Docs PR for https://github.com/arangodb/arangodb/pull/16380
> Added a new language to the snowball list

- 3.10/administration-license.md
- 3.10/upgrading-community-to-enterprise.md
- 3.7/deployment-kubernetes-usage.md
- 3.9/administration-license.md
- 3.9/upgrading-community-to-enterprise.md
- added info about license key when upgrading to Enterprise edition
- added info about license key for Kubernetes deployments
> License key

- drivers/java-reference-setup.md
Added documentation about thread safety in Java Driver.
> Java Driver thread safety

- 3.10/indexing-index-basics.md
- 3.10/release-notes-new-features310.md
https://github.com/arangodb/arangodb/pull/16253
> [APM-135] Parallelism in non-unique index creation

- 3.10/data-modeling-documents-computed-values.md
- 3.10/highlights.md
- _data/3.10-manual.yml
Initial documentation for the computed values feature.
TBD in a separate PR:
- Release notes
- Examples
- HTTP API
https://deploy-preview-1059--zealous-morse-14392b.netlify.app/docs/3.10/data-modeling-documents-computed-values.html
> DOC-123 | Document computed attributes APM-199

- 3.10/aql/execution-and-performance-optimizer.md
- 3.10/release-notes-new-features310.md
Docs PR for https://github.com/arangodb/arangodb/pull/16481
Preview:
- https://deploy-preview-1049--zealous-morse-14392b.netlify.app/docs/3.10/release-notes-new-features310.html#index-lookup-optimization
- https://deploy-preview-1049--zealous-morse-14392b.netlify.app/docs/3.10/aql/execution-and-performance-optimizer.html#filter-projections-optimizations
> Optimization for index post-filtering (early pruning)

- drivers/dotnet.md
This is a small section on the driver homepage that gives information about new features of each new release.
> Added Whats New section for dotnet driver

- 3.10/aql/operations-replace.md
- 3.10/aql/operations-update.md
- 3.8/aql/operations-replace.md
- 3.8/aql/operations-update.md
- 3.9/aql/operations-replace.md
- 3.9/aql/operations-update.md
> AQL: Clarify that UPDATE/REPLACE can target a different collection than what a FOR loop read from

- 3.10/programs-arangod-rocksdb.md
- 3.11/programs-arangod-rocksdb.md
- 3.9/programs-arangod-rocksdb.md
Documentation PR for the following arangodb/arangodb PRs:
* devel: https://github.com/arangodb/arangodb/pull/16982
* 3.10: https://github.com/arangodb/arangodb/pull/16982
* 3.9: https://github.com/arangodb/arangodb/pull/16980
> Added startup option `--rocksdb.periodic-compaction-ttl`

- 3.10/graphs-pregel-algorithms.md
- 3.11/graphs-pregel-algorithms.md
Updated the description of HITS, added the description of the original version of the algorithm.
> Updated the description of HITS

- oasis/deployments.md
preview: https://deploy-preview-1102--zealous-morse-14392b.netlify.app/docs/3.10/oasis/deployments.html#how-to-edit-a-deployment
> DOC-157/Oasis - How to edit a deployment

- 3.10/arangosync.md
- 3.10/troubleshooting-dc2dc.md
- 3.11/arangosync.md
- 3.11/troubleshooting-dc2dc.md
- 3.7/troubleshooting-dc2-dc.md
- updated limitations, added ARM64 support
- added note for document size limitations
> DOC-179/arangosync-update

- 3.11/aql/execution-and-performance-query-statistics.md
- 3.11/release-notes-api-changes311.md
Docs PR for https://github.com/arangodb/arangodb/pull/17029
> return number of intermediate commits for AQL queries

- 3.10/release-notes-upgrading-changes310.md
Document some internal changes to RocksDB for version 3.10, which have been missing before.
> document some RocksDB changes

- 3.10/programs-arangod-arangosearch.md
- 3.11/programs-arangod-arangosearch.md
- 3.9/programs-arangod-arangosearch.md
Documentation PR for:
* 3.9.4: https://github.com/arangodb/arangodb/pull/16979
* 3.10: https://github.com/arangodb/arangodb/pull/16971
* devel: https://github.com/arangodb/arangodb/pull/16900
> added documentation for skipping link recovery

- 3.10/data-science-pyg-adapter.md
- 3.11/data-science-pyg-adapter.md
- 3.9/data-science-pyg-adapter.md
- _data/3.10-manual.yml
- _data/3.11-manual.yml
- _data/3.9-manual.yml
https://deploy-preview-1114--zealous-morse-14392b.netlify.app/docs/3.10/data-science-pyg-adapter.html
> DOC-191/added PyG Adapter documentation

- _data/3.10-manual.yml
- _data/3.11-manual.yml
- styles/site.css
- created the About ArangoDB chapter
- changed description of on-page table of contents from "Table of contents" to "On this page"
> Created About ArangoDB chapter

- 3.10/programs-arangorestore-examples.md
- 3.11/programs-arangorestore-examples.md
- 3.8/programs-arangorestore-examples.md
- 3.9/programs-arangorestore-examples.md
Documentation adjustment after https://arangodb.atlassian.net/browse/BTS-1081.
> documentation for BTS-1081

- 3.10/analyzers.md
- 3.10/aql/functions-arangosearch.md
- 3.10/arangosearch-nested-search.md
- 3.10/arangosearch-search-highlighting.md
- 3.10/arangosearch-views.md
- 3.10/arangosearch.md
- 3.10/indexing-inverted.md
- 3.10/indexing-working-with-indexes.md
- 3.10/quick-start-in-the-cloud.md
- 3.10/release-notes-new-features310.md
- 3.11/analyzers.md
- 3.11/aql/functions-arangosearch.md
- 3.11/arangosearch-nested-search.md
- 3.11/arangosearch-search-highlighting.md
- 3.11/arangosearch-views.md
- 3.11/arangosearch.md
- 3.11/indexing-inverted.md
- 3.11/indexing-working-with-indexes.md
- 3.8/aql/functions-arangosearch.md
- 3.9/aql/functions-arangosearch.md
Updates 3.10 and 3.11 examples but without user-visible changes.
> DOC-216 | ArangoSearch v3.10.1

- 3.10/installation-windows.md
- 3.11/installation-windows.md
- 3.8/installation-windows.md
- 3.9/installation-windows.md
Changed warning about using Windows in production
> Warning Installation Windows

- 3.10/arangosearch-nested-search.md
- 3.10/data-modeling-documents-computed-values.md
- 3.10/foxx-reference-routers-response.md
- 3.10/indexing-inverted.md
- 3.11/arangosearch-nested-search.md
- 3.11/data-modeling-documents-computed-values.md
- 3.11/foxx-reference-routers-response.md
- 3.11/indexing-inverted.md
- 3.8/foxx-reference-routers-response.md
- 3.9/foxx-reference-routers-response.md
- Fix description of overwrite option for Computed Values
- Inverted index nested / storedValues fixes
- Foxx response object: missing negation, style
> Random-fixes-2022-12-16

- _data/arangograph.yml
- arangograph/single-sign-on.md
First draft for ArangoGraph SSO and SCIM.
> ArangoGraph SSO and SCIM

- 3.10/features-community-edition.md
- 3.10/release-notes-new-features310.md
- 3.11/features-community-edition.md
Also download page: https://github.com/arangodb/oskar/pull/482
> DOC-328 | ARM support is limited to Little Endian

- 3.10/aql/index.md
- 3.10/architecture-deployment-modes-cluster-sharding.md
- 3.10/architecture-storage-engines.md
- 3.10/data-modeling-graphs-from-rdf.md
- 3.10/deployment-oneshard.md
- 3.10/graphs-enterprise-graphs-getting-started.md
- 3.10/highlights.md
- 3.10/release-notes-new-features36.md
- 3.11/administration-cluster.md
- 3.11/aql/index.md
- 3.11/architecture-deployment-modes-cluster-sharding.md
- 3.11/architecture-storage-engines.md
- 3.11/deployment-oneshard.md
- 3.11/features-enterprise-edition.md
- 3.11/release-notes-new-features36.md
Follow-up to #1246 (DOC-317), plus some random improvements.
> OneShard follow-up

- 3.10/backup-restore.md
- 3.11/backup-restore.md
Small changes to improve clarity as requested by the support team.
> DOC-295 | Clarifications - Global Write Transaction Lock

- 3.10/aql/execution-and-performance-optimizer.md
- 3.11/aql/execution-and-performance-optimizer.md
- 3.11/release-notes-new-features311.md
- 3.9/aql/execution-and-performance-optimizer.md
Also adjust statement about number-suffixed optimizer rules and remove now obsolete rule from list
> DOC-458 | MDS-1001 | Optimize access to last element in traversal

- 3.10/aql/fundamentals-syntax.md
- 3.10/data-model-and-concepts.md
- 3.10/features.md
- 3.11/aql/fundamentals-syntax.md
- 3.11/data-model-and-concepts.md
- 3.11/features.md
https://discourse.gohugo.io/t/whitespace-control-in-shortcode-call/43743
> Move start of `{% comment %}` block to adjacent line in table for Hugo toolchain

- 3.11/release-notes-api-changes311.md
- 3.11/release-notes-upgrading-changes311.md
Mention a downwards-incompatible change.
> mention downwards-incompatible change

- 3.10/aql/functions-fulltext.md
- 3.11/aql/functions-fulltext.md
> Add deprecation notice to AQL fulltext functions

- 3.10/administration-cluster.md
- 3.11/administration-cluster.md
- 3.12/administration-cluster.md
- 3.9/administration-cluster.md
I recently had to remind myself how the `CleanOutServer` job works and therefore I searched the docs for it. Now that I'm done, I'll leave here a couple of suggestions, for better readability and clarity.
Note that I left out 3.8 and 3.7.
> Suggesting changes for better readability and clarity

- 3.10/aql/functions-document.md
- 3.11/aql/functions-document.md
- 3.12/aql/functions-document.md
- 3.9/aql/functions-document.md
https://github.com/arangodb/arangodb/issues/19259
> Add hint about `MERGE()` vs `ZIP()` performance

- 3.10/aql/fundamentals-syntax.md
- 3.11/aql/fundamentals-syntax.md
- 3.12/aql/fundamentals-syntax.md
- Remove incorrect and out-of-place statement about collection limit per query
- Move content about collection names to the existing section
- Add shadowing example
> Improve statements about AQL names

- 3.10/release-notes-new-features310.md
- 3.11/release-notes-new-features311.md
- 3.12/release-notes-new-features312.md
Upstreams: 
3.10: https://github.com/arangodb/arangodb/pull/19471
> Release notes: Add `--database.max-databases` in 3.10

- 3.12/release-notes-new-features312.md
Upstreams:
- devel: https://github.com/arangodb/arangodb/pull/19472
> Release notes for .sst file partitioning

- 3.12/release-notes-api-changes312.md
Docs PR for https://github.com/arangodb/arangodb/pull/19641
> expose endianness

- 3.12/release-notes-new-features312.md
Upstreams:
- 3.12: https://github.com/arangodb/arangodb/pull/19628
- 3.11: https://github.com/arangodb/arangodb/pull/19682
- 3.10: https://github.com/arangodb/arangodb/pull/19681
> DOC-522 | Update Swagger UI
