arangodb/docs

3.5/indexing-ttl.md

Clarify how to use time-zoned values in the TTL index.

clarify timezone handling

---

3.4/graphs-pregel.md
3.5/graphs-pregel.md

https://github.com/arangodb/team-orco-planning/issues/135

add pregel `shardKeyAttribute` to documentations

---

3.5/http/analyzers.md

Renamed text and norm analyzer parameters.
Fixed default value for accent in norm analyzer section.

Bug fix/rename analyzer stem norm properties

---

3.4/aql/functions-date.md
3.4/release-notes-upgrading-changes34.md
3.5/aql/functions-date.md
3.5/release-notes-upgrading-changes34.md

Document behavior change as detected in issue https://github.com/arangodb/planning/issues/4226

fix planning issue 4226

---

3.4/drivers/index.md
3.5/architecture-storage-engines.md
3.5/cookbook/cloud-node-js-docker.md
3.5/cookbook/compiling-debian.md
3.5/cookbook/compiling-windows.md
3.5/cookbook/index.md
3.5/cookbook/use-cases-exporting-data.md
3.5/deployment-active-failover-manual-start.md
3.5/deployment-active-failover-using-the-starter.md
3.5/deployment-cluster-manual-start.md
3.5/deployment-cluster-using-the-starter.md
3.5/deployment-single-instance-manual-start.md
3.5/deployment-single-instance-using-the-starter.md
3.5/drivers/go-getting-started.md
3.5/drivers/index.md
3.5/drivers/java-reference-serialization.md
3.5/getting-started-web-interface.md
3.5/graphs-pregel.md
3.5/http/general.md
3.5/http/repairs.md
3.5/installation.md
3.5/release-notes-new-features26.md
3.5/release-notes-upgrading-changes34.md
3.5/security-security-options.md
3.5/upgrading-manually-active-failover.md
3.5/upgrading-manually-cluster.md
3.5/upgrading-starter.md

Check 3.5\cookbook\use-cases-exporting-data.md in particular, as it uses `[label][n]{:attrs}` syntax

Fix free-text links

---

_config.yml
sitemap.rb

We need a sitemap.xml, but the one generated by jekyll-sitemap plugin does not include the canonical links (stable version).
Pantheon's .gitignore rules prevented the docs sitemap from being committed, so there was none available so far at https://www.arangodb.com/docs/sitemap.xml. Changed in dev env:
```diff
commit 28f9ab4f914b2a4e9219ec02cab8216ca25b0518
tree e163edd3e8f806cf91c6434340ee11d250727c89
parent 2e8456b5534536e07cf0bac335d5dcf2e06a5ec8
Add exception for docs sitemap to .gitignore
diff --git a/.gitignore b/.gitignore
index 0b55b14..31da344 100644
--- a/.gitignore
+++ b/.gitignore
@@ -15,6 +15,9 @@ sitemap.xml
sitemap.xml.gz
*.log
+# Documentation
+!docs/sitemap.xml
+
wp-content/cache/
wp-content/backups/
```

Temporary script for manual sitemap generation

---

3.4/smartjoins.md
3.5/aql/functions-arangosearch.md
3.5/aql/operations-search.md
3.5/arangosearch-analyzers.md
3.5/arangosearch-examples.md
3.5/arangosearch-views.md
3.5/arangosearch.md
3.5/drivers/java-reference-view-arangosearch.md
3.5/http/views-arangosearch.md
3.5/smartjoins.md
3.6/aql/functions-arangosearch.md
3.6/aql/operations-search.md
3.6/arangosearch-analyzers.md
3.6/arangosearch-examples.md
3.6/arangosearch-views.md
3.6/arangosearch.md
3.6/drivers/java-reference-view-arangosearch.md
3.6/http/views-arangosearch.md
3.6/smartjoins.md

To be tested: does the space in front of `#` matter? Do the 3.5 and 3.6 redirects work and not overwrite 3.4 pages?

Fix redirects for stable = 3.5

---

3.4/programs-starter-options.md
3.5/programs-starter-options.md
3.6/programs-starter-options.md

Doc - fixed typo for option: "--auth.jwt-secret"

---

3.5/aql/execution-and-performance-optimizer.md
3.6/aql/execution-and-performance-optimizer.md

There is apparently a new optimizer rule `move-filter-into-enumerate`:
https://github.com/arangodb/arangodb/pull/10159
@jsteemann Can you add a brief description please? (see https://github.com/arangodb/docs/pull/187/commits/9021981f1d1dbe289b337f8ee47131fdd83d522b)
Are we missing any other rules?

Update AQL Optimizer page

---

Gemfile.lock

jekyll-algolia plugin is not maintained, hence no deps bump to be expected

Adjust Gemfile.lock to require newer nokogiri

---

3.5/programs-arangobackup-examples.md
3.6/programs-arangobackup-examples.md

So the syntax is `<key>:<path>`  where `<key>` is a top level attribute key (here: `my-local`)?
```
{
"my-local": {
"type": "local",
"copy-links": "false",
"links": "false",
"one_file_system": "false"
}
}
```

Backup: Rclone config requires quotes around true and false / multi config

---

3.5/aql/functions-arangosearch.md
3.5/arangosearch-analyzers.md
3.5/arangosearch-views.md
3.6/aql/functions-arangosearch.md
3.6/arangosearch-analyzers.md
3.6/arangosearch-views.md

- PHRASE() function also accepts an array with phraseParts and skipTokens
- table alignment
- moved questions/notes to https://github.com/arangodb/docs/issues/222

ArangoSearch refactor (part 2)

---

3.6/aql/invocation-with-arangosh.md
3.6/release-notes-new-features36.md

I think https://www.arangodb.com/docs/stable/aql/invocation-with-arangosh.html#setting-options is not the best location for options. I think It is a bit too hidden.

add documentation for query timeout

---

3.6/aql/execution-and-performance-optimizer.md
3.6/release-notes-new-features36.md

GATHER and REMOTE do not prevent subquery splicing anymore.

Remove GATHER and REMOTE from the subquery splicing naughty list

---

3.6/aql/execution-and-performance-optimizer.md
3.6/release-notes-new-features36.md

Followup to #218 .
* Clarify that only `COLLECT WITH COUNT INTO` is affected, and no other `COLLECT` variants
* Avoid a possible misinterpretation that an unsuitable subquery would make contained subqueries recursively unsuitable

Clarified two things about splice-subqueries

---

_includes/topnav.html
_layouts/default.html
netlify.sh

Can be checked in Liquid template via `jekyll.environment`
Partially related to #79. It should fix the version switcher in Netlify previews, but not the redirects #95.

Set JEKYLL_ENV environment variable for Netlify builds

---

3.5/http/transaction-stream-transaction.md
3.6/http/transaction-stream-transaction.md
3.7/http/transaction-stream-transaction.md

I suppose the General Graphs JS API uses the Gharial HTTP API, so this should be correct. I'm not sure what "supports stream transactions" means exactly however.

General Graphs API supported in Stream Transactions since v3.5.1

---

3.6/architecture-deployment-modes-cluster-architecture.md

The sharding option "single" of a database (OneShard) is irreversible and all collections behave the same.

OneShard restriction

---

3.7/aql/operators.md
3.7/release-notes-new-features37.md

https://github.com/arangodb/arangodb/pull/10634
Unsure if this should be documented at all, if it's a pure performance optimization. Or were there cases where the double-evaluation led to side effects?

Document change to ternary operator evaluation

---

3.6/drivers/spring-data.md
3.7/drivers/spring-data.md
_data/3.6-drivers.yml
_data/3.7-drivers.yml
_plugins/NavigationTag.rb
js/site.js

Open external links in new tab (noopener noreferrer), use `fa fa-external-link` to indicate such entries:
```yaml
- text: Reference
href: java-reference.html
children:
- text: JavaDoc
href: http://arangodb.github.io/arangodb-java-driver/
- text: JavaDoc VelocyPack
href: http://arangodb.github.io/java-velocypack/
```

Allow external links in navigation

---

3.4/drivers/go-getting-started.md
3.5/drivers/go-getting-started.md
3.5/programs-arangodump-examples.md
3.6/drivers/go-connection-management.md
3.6/drivers/go-getting-started.md
3.6/drivers/java-reference-setup.md
3.6/programs-arangodump-examples.md
3.7/drivers/go-connection-management.md
3.7/drivers/go-getting-started.md
3.7/drivers/java-reference-setup.md
3.7/programs-arangodump-examples.md

Looks like the Go driver has a setting ConnLimit. Is that all it takes for connection pooling?

Driver connection pooling

---

3.7/aql/execution-and-performance-optimizer.md

This rule has been removed
Wait for https://github.com/arangodb/arangodb/pull/11400 to be merged before this is merged.

Remove mention of scatter-arangosearch-view-in-cluster

---

3.7/release-notes-new-features37.md
3.8/release-notes-new-features37.md

Fix a non-working example query for query helper options.
Found while testing https://arangodb.atlassian.net/browse/QA-46

fix an error in the docs.

---

3.7/aql/functions-arangosearch.md
3.8/aql/functions-arangosearch.md

Links for ngram_similarity and ngram_positional_similarity don't point to expected String Functions pages.
- I believe I have followed correct format for links but please advise if not.

Fixed similarity links

---

3.7/aql/functions-arangosearch.md
3.7/highlights.md
3.7/release-notes-new-features37.md
3.8/highlights.md

Comment out LIKE() function content, remove reference from highlights.

Hide wildcard search content for 3.7 GA

---

3.7/http/replications-replication-dump.md

The feature was disabled for 3.7 GA and the docublocks are thus missing.
References: #361, #473 and https://github.com/arangodb/arangodb/pull/11935 
Related: https://github.com/arangodb/arangodb/pull/12392

Remove Merkle tree docublock tags from 3.7

---

3.7/aql/functions-miscellaneous.md
3.8/aql/functions-miscellaneous.md

It's like NOOPT(), but marked as deterministic.
https://github.com/arangodb/arangodb/blob/d9a4abfd7b9aaad3d35756a5aae3ca632b10722e/arangod/Aql/AqlFunctionFeature.cpp#L453

Document NOEVAL() internal function

---

3.3/aql/operations-upsert.md
3.4/aql/operations-remove.md
3.4/aql/operations-replace.md
3.4/aql/operations-update.md
3.4/aql/operations-upsert.md
3.5/aql/operations-remove.md
3.5/aql/operations-replace.md
3.5/aql/operations-update.md
3.5/aql/operations-upsert.md
3.6/aql/operations-remove.md
3.6/aql/operations-replace.md
3.6/aql/operations-update.md
3.6/aql/operations-upsert.md
3.7/aql/operations-remove.md
3.7/aql/operations-replace.md
3.7/aql/operations-update.md
3.7/aql/operations-upsert.md
3.8/aql/operations-remove.md
3.8/aql/operations-replace.md
3.8/aql/operations-update.md
3.8/aql/operations-upsert.md

Before I get this out of Draft I need to back port the statement to all released versions.

Added a clarification on intermediate commits and upsert

---

3.8/release-notes-upgrading-changes38.md

Docs for https://github.com/arangodb/arangodb/pull/12605

Fixed #12605: If unset sub-document is to be updated, keepNull is ignored

---

3.8/data-modeling-collections-database-methods.md
3.8/release-notes-upgrading-changes38.md

Documentation update for https://github.com/arangodb/arangodb/pull/12866
Remove remainders of non-functional collection attributes indexBuckets, journalSize, doCompact, isVolatile from the code.
The attributes were useful for the MMFiles storage engine only, and can be completely ignored for the RocksDB engine.

remove obsoleted collection attributes

---

3.3/foxx-graph-ql.md
3.4/foxx-reference-modules-graph-ql.md
3.5/foxx-reference-modules-graph-ql.md
3.6/foxx-reference-modules-graph-ql.md
3.7/foxx-reference-modules-graph-ql.md
3.8/appendix-java-script-modules.md
3.8/foxx-reference-modules-graph-ql.md

@pluma I think this doesn't go far enough yet. WDYT about moving the part about 0.12+ up, and move the legacy stuff to the bottom, under a separate headline?

Foxx: graphql-sync is deprecated

---

3.4/release-notes.md
3.5/release-notes.md
3.6/release-notes.md
3.7/release-notes.md
3.8/release-notes.md

It's considered internal only and not shared with Enterprise customers.
Fixes #590

Remove link to Arangosync changelog

---

_layouts/default.html
_plugins/ExtraFilters.rb

More generic fix than #589, which also fixes the GitHub Contribute link for the release notes, drivers etc.
The path separator is apparently `/` on Windows as well, so it looks like no special processing is needed to go from `page['path']` to realpath to relative URL path.

Add resolve_symlink filter to get relative source file path

---

3.3/appendix-java-script-modules.md
3.3/foxx-graph-ql.md
3.3/release-notes-new-features21.md
3.3/release-notes-new-features24.md
3.3/release-notes-new-features26.md
3.4/appendix-java-script-modules.md
3.4/foxx-reference-modules-graph-ql.md
3.4/release-notes-new-features21.md
3.4/release-notes-new-features24.md
3.4/release-notes-new-features26.md
3.5/appendix-java-script-modules.md
3.5/foxx-reference-modules-graph-ql.md
3.5/programs-arangobackup-examples.md
3.6/appendix-java-script-modules.md
3.6/foxx-reference-modules-graph-ql.md
3.6/programs-arangobackup-examples.md
3.7/appendix-java-script-modules.md
3.7/foxx-reference-modules-graph-ql.md
3.7/programs-arangobackup-examples.md
3.7/release-notes-new-features21.md
3.7/release-notes-new-features24.md
3.7/release-notes-new-features26.md
3.8/foxx-reference-modules-graph-ql.md
3.8/programs-arangobackup-examples.md

- Fix link to drivers page.
- Fix link to post "Document your Foxx apps with Swagger 2".
- Fix links to "Building Hypermedia APIs" blog series.
- Fix rclone.org links.
- Fix link to `graphql-sync` module (from [not exists github repository](https://github.com/arangodb/graphql-sync) to [NPM page](https://www.npmjs.com/package/graphql-sync).

Fix broken links

---

3.4/aql/tutorial-geospatial.md
3.5/aql/tutorial-geospatial.md
3.6/aql/tutorial-geospatial.md
3.7/aql/tutorial-geospatial.md
3.8/aql/tutorial-geospatial.md

Don't use deprecated functions NEAR() and WITHIN() in AQL tutorial

---

3.4/drivers/java-reference-setup.md
3.7/drivers/java-reference-setup.md

Added Java driver VST Keep-Alive configuration documentation.

Java driver VST Keep-Alive configuration

---

3.8/release-notes-upgrading-changes38.md

@simran-b: as discussed, here is the adjustment for the memory usage limits.
This is the docs PR for https://github.com/arangodb/arangodb/pull/13595

adjust memory limit formula for small installations

---

3.8/aql/execution-and-performance-optimizer.md
3.8/release-notes-upgrading-changes38.md

Adjust the docs for 3.8 so they mention the optimizer rule `splice-subqueries` cannot be turned off anymore.

adjust docs for changed splice-subqueries optimizer rule behavior

---

3.6/data-modeling-databases-working-with.md
3.6/programs-arangod-query.md
3.6/programs-arangodump-examples.md
3.6/smartjoins.md
3.7/data-modeling-databases-working-with.md
3.7/programs-arangod-audit.md
3.7/programs-arangod-log.md
3.7/programs-arangod-query.md
3.7/programs-arangodump-examples.md
3.7/smartjoins.md
3.8/data-modeling-databases-working-with.md
3.8/programs-arangod-audit.md
3.8/programs-arangod-log.md
3.8/programs-arangod-query.md
3.8/programs-arangodump-examples.md
3.8/smartjoins.md

Fix wrong version numbers introduced for backported logging options.
The docs say the options are available in 3.7.8, and that was also the idea.
However, 3.7.8 was built based on 3.7.7 with just a single commit on top, and that rendered all plans invalid.
This PR fixes the version number in the docs to 3.7.9, which will be the _real_ release these options become available.

fix wrong version number for new options

---

3.4/aql/fundamentals-data-types.md
3.4/aql/operators.md
3.5/aql/fundamentals-data-types.md
3.5/aql/operators.md
3.6/aql/fundamentals-data-types.md
3.6/aql/operators.md
3.7/aql/fundamentals-data-types.md
3.7/aql/operators.md
3.8/aql/fundamentals-data-types.md
3.8/aql/operators.md

Fixes #626 and addresses the documentation-portion of https://github.com/arangodb/arangodb/issues/13655

Correct statements about value comparisons

---

3.8/release-notes-new-features38.md
3.8/release-notes-upgrading-changes38.md

Warn more explicitly about downwards-incompatible changes.

warn about downwards-incompatible changes

---

3.8/programs-arangod-server.md
3.8/release-notes-new-features38.md
3.8/tutorials-reduce-memory-footprint.md

This PR adds a description of our cluster overwhelm measures in 3.8
to the new features for 3.8 document. It also explains the new command
line option `--server.ongoing-low-priority-multiplier` .

New features 3.8 and cluster overwhelm

---

3.8/appendix-deprecated.md

Add deprecation notice to 3.8 appendix for old metrics API.

Deprecate old metrics API

---

3.6/installation-linux-osconfiguration.md
3.7/installation-linux-osconfiguration.md
3.8/installation-linux-osconfiguration.md

Server fails to start on some systems:
```
FATAL [7ef60] {config} specified language 'en_US' does not match previously used language ''
```
Related issues:
- https://github.com/arangodb/arangodb/issues/12501
- https://github.com/arangodb/arangodb/issues/8332
It's unclear how it gets into this situation and whether starting the server initially with an explicit `default-language` would help in such cases. We should also add information about how to switch it (dump & restore) and potentially improve the server error message in cases where there is no system locale.

Add section about missing locale on Linux / language mismatch on startup

---

3.3/administration-arangoimp.md
3.4/programs-arangoimport-examples-csv.md
3.5/programs-arangoimport-examples-csv.md
3.6/programs-arangoimport-examples-csv.md
3.7/programs-arangoimport-examples-csv.md
3.8/programs-arangoimport-examples-csv.md
3.9/programs-arangoimport-examples-csv.md

In 3.7+ it depends on the --convert option
Related issues:
- arangodb/arangodb#13169
- arangodb/arangodb#13924
- arangodb/arangodb#13965

Unquoted null, false and true are always converted in 3.6

---

3.4/programs-arangod-global.md
3.5/programs-arangod-global.md
3.6/administration-configuration.md
3.6/aql/fundamentals-type-value-order.md
3.6/indexing-persistent.md
3.6/installation-linux-osconfiguration.md
3.6/programs-arangod-general.md
3.7/administration-configuration.md
3.7/aql/fundamentals-type-value-order.md
3.7/indexing-persistent.md
3.7/installation-linux-osconfiguration.md
3.7/programs-arangod-general.md
3.8/administration-configuration.md
3.8/aql/fundamentals-type-value-order.md
3.8/indexing-persistent.md
3.8/installation-linux-osconfiguration.md
3.8/programs-arangod-general.md
3.9/administration-configuration.md
3.9/aql/fundamentals-type-value-order.md
3.9/indexing-persistent.md
3.9/installation-linux-osconfiguration.md
3.9/programs-arangod-general.md
_data/3.6-manual.yml
_data/3.7-manual.yml
_data/3.8-manual.yml
_data/3.9-manual.yml
_includes/program-option.html
_plugins/OptionsBySectionFilter.rb

Rename global to general options
Could restrict this to 3.9+ but doesn't have any side effects. Older binaries call it global, that's it.
https://github.com/arangodb/arangodb/pull/13982/commits/3956da173731178184fc0a20fbfdb0a75f8249b0
Fixes https://github.com/arangodb/planning/issues/3318
Depends on #683 to get a preview build.

Startup option section: global / general

---

3.8/appendix-deprecated.md
3.8/data-modeling-collections-collection-methods.md
3.9/appendix-deprecated.md
3.9/data-modeling-collections-collection-methods.md

Deprecate collection loading/unloading, as there is no sensible use case for it anymore with RocksDB.

deprecate load/unload functions for collections

---

3.8/programs-arangod-log.md
3.8/release-notes-new-features38.md
3.9/programs-arangod-log.md

The correct option is "log.line-number" not "log.file-name".

fixed typo

---

3.8/analyzers.md
3.9/analyzers.md

Added warning denoting limitation for pipeline analyzer: geo-related analyzers could not be used in pipeline.
See the issue https://arangodb.atlassian.net/browse/BTS-462

add warning

---

3.6/aql/functions-arangosearch.md
3.7/aql/functions-arangosearch.md
3.7/aql/functions-string.md
3.7/aql/operations-search.md
3.7/arangosearch-exact-value-matching.md
3.7/arangosearch-performance.md
3.7/arangosearch-wildcard-search.md
3.7/highlights.md
3.8/aql/functions-arangosearch.md
3.8/aql/functions-string.md
3.8/aql/operations-search.md
3.8/arangosearch-exact-value-matching.md
3.8/arangosearch-performance.md
3.8/arangosearch-wildcard-search.md
3.8/highlights.md
3.8/release-notes-new-features38.md
3.9/aql/functions-arangosearch.md
3.9/aql/functions-string.md
3.9/aql/operations-search.md
3.9/arangosearch-exact-value-matching.md
3.9/arangosearch-performance.md
3.9/arangosearch-wildcard-search.md
3.9/highlights.md

- BTS-399: An n-gram Analyzer with min == max is expected by NGRAM_MATCH(), it isn't just a recommendation (score will be lower than expected otherwise)
- Remove `countApproximate` option from 3.7 docs (added only in 3.8)
- Approximate count (`countApproximate: "cost"`) is affected by the eventually consistent nature of Views, i.e. it is not precise if documents were recently changed because everything View-related is lagging behind
- Remove erroneous link JACCARD() function . Proximity search is PHRASE() with skip tokens (wildcards)
- Fix headline level of STARTS_WITH()
- The SEARCH `conditionOptimization` option was introduced in 3.6.2, not 3.7.0
- Replace absolute with relative query execution time in `EXISTS()` example
- PHRASE() skips empty arrays since 3.6.1

ArangoSearch clarifications

---

drivers/spark-connector-getting-started.md

This PR updates the ArangoDB Spark Connector version and clarifies Spark version compatibilities (based on Scala versions used - 2.11 is deprecated as of 2.4.1)

Update Spark Connector Packages & Versions

---

3.8/arangosearch-faceted-search.md
3.8/arangosearch.md
3.9/arangosearch-faceted-search.md
3.9/arangosearch.md
_data/3.8-manual.yml
_data/3.9-manual.yml

APM-59
Only adding it to 3.8 and 3.9 as 3.7 does not support the `countApproximate` option.
https://deploy-preview-724--zealous-morse-14392b.netlify.app/docs/3.8/arangosearch-faceted-search.html

ArangoSearch: Add faceted search example

---

3.7/aql/functions-arangosearch.md
3.8/aql/functions-arangosearch.md
3.9/aql/functions-arangosearch.md

doc update after implementing prefix in levenshtein_match
https://github.com/arangodb/arangodb/pull/14413

prefix in LEVENSHTEIN_MATCH

---

3.6/administration-managing-users.md
3.7/administration-managing-users.md
3.8/administration-managing-users.md
3.9/administration-managing-users.md

`server.authentication-system-only` disables authentication for Foxx endpoints only

---

3.8/analyzers.md
3.8/highlights.md
3.9/analyzers.md
3.9/generated/Examples/analyzerCollation.generated
3.9/generated/Examples/analyzerSegmentationBreak.generated
3.9/highlights.md
3.9/release-notes-new-features39.md

- Uncomment `stopword` Analyzer
- Add language-agnostic `segmentation` Analyzer
- Add `collation` Analyzer
https://github.com/arangodb/arangodb/pull/13759
https://github.com/arangodb/arangodb/pull/14542

add description of newly added arangosearch analyzers

---

3.7/transactions-limitations.md
3.8/transactions-limitations.md
3.9/transactions-limitations.md

Currently we have mentioned limitations for Stream Transactions in our HTTP documentation, but not in the general "Limitations" section for transactions. 
I think the limitations should be mentioned in both places.
The PR copies the limitations paragraph from the HTTP API into the general space. This is redundant, so it is not ideal. Is there a way to write a paragraph once and use it from multiple places in the docs?

mention extra limitations for Stream Transactions

---

3.7/aql/functions-arangosearch.md
3.8/aql/functions-arangosearch.md
3.9/aql/functions-arangosearch.md

Add hint about LEVENSHTEIN_MATCH `prefix` argument

add hint: LEVENSHTEIN_MATCH() expects `target` value excluding the `prefix`

---

3.7/aql/examples-combining-queries.md
3.7/aql/fundamentals-limitations.md
3.7/aql/operators.md
3.8/aql/examples-combining-queries.md
3.8/aql/fundamentals-limitations.md
3.8/aql/operators.md
3.9/aql/examples-combining-queries.md
3.9/aql/fundamentals-limitations.md
3.9/aql/operators.md

- Extend subquery examples
- Add remarks about ternary operator with subqueries
- Relates to
- arangodb/arangodb#14463
- arangodb/arangodb#14544
- arangodb/arangodb#2474
- arangodb/arangodb#1624
TODO: Apply to 3.7+3.8 after review.

Add details about subqueries and ternary operator

---

3.9/release-notes-new-features39.md

https://github.com/arangodb/arangodb/pull/14599

Added description for Analyzers Web UI.

---

3.8/aql/examples-upsert-repsert.md
3.9/aql/examples-upsert-repsert.md
3.9/examples-upsert-repsert.md
_data/3.8-aql.yml
_data/3.9-aql.yml

Mostly about AQL UPSERT and INSERT with overwriteMode, but also mentions Document API.
UPSERT `exclusive` option not mentioned even though it makes it effectively atomic, because there were issues with exclusive locks in the past blocking progress.
Unclear how much faster Document API is compared to `FOR doc IN @arr INSERT doc ...`, but it will always perform better, because it sends the documents to the respective DB-Servers without the overhead of AQL. AQL needs to do a setup and shutdown round, sending a message to all participating DB-Servers, and possibly require additional communication.

Guide about conditionally inserting & updating/replacing documents

---

3.5/release-notes-new-features35.md
3.6/release-notes-new-features36.md
3.7/deployment-kubernetes-metrics.md
3.7/release-notes-new-features37.md
README.md
_plugins/ExtraFilters.rb
drivers/spring-data-reference-mapping-indexes.md

It's more cumbersome to use than the previous string comparison but it will handle versions like 3.10 correctly because it compares numerically

Implement new version filter for conditional content

---

3.10/programs-arangod-server.md
3.6/programs-arangod-server.md
3.7/programs-arangod-server.md
3.8/programs-arangod-server.md
3.9/programs-arangod-server.md

Add missing description for --server.maximal-threads default value

---

3.10/release-notes-new-features310.md
3.9/release-notes-new-features39.md

(in contrast to the branch name, the upgrade is actually to 6.26, not 6.25 - this is due to 6.26 being released after the upgrade branch was created)

RocksDB 6.26

---

3.10/administration-cluster.md
3.10/appendix-glossary.md
3.10/aql/examples-actors-and-movies.md
3.10/aql/execution-and-performance-optimizer.md
3.10/aql/execution-and-performance-query-profiler.md
3.10/arangosearch-performance.md
3.10/architecture-deployment-modes-cluster-sharding.md
3.10/http/indexes-skiplist.md
3.10/http/indexes.md
3.10/http/replications-walaccess.md
3.10/indexing-working-with-indexes.md
3.10/security-auditing-audit-events.md
3.9/administration-cluster.md
3.9/appendix-glossary.md
3.9/aql/examples-actors-and-movies.md
3.9/aql/execution-and-performance-optimizer.md
3.9/aql/execution-and-performance-query-profiler.md
3.9/arangosearch-performance.md
3.9/architecture-deployment-modes-cluster-sharding.md
3.9/http/indexes-skiplist.md
3.9/http/indexes.md
3.9/http/replications-walaccess.md
3.9/indexing-working-with-indexes.md
3.9/security-auditing-audit-events.md

in the RocksDB engine, a skiplist index is the same as a persistent
index. it is just an alias and there for compatibility reasons. we
should discourage the usage of "skiplist" indexes and instead use and
recommend "persistent" indexes.

remove usages of "skiplist"

---

drivers/spring-data-reference-mapping-indexes.md
drivers/spring-data-reference-mapping.md
drivers/spring-data-reference-template-collection-manipulation.md

Follow-up of https://github.com/arangodb/docs/pull/805

removed skiplist index references from Spring Data documentation

---

3.10/appendix-deprecated.md
3.9/appendix-deprecated.md
3.9/release-notes-upgrading-changes39.md

Documentation for a deprecation discussed turing team lead sync meeting today:
* deprecate _arangoimp_ alias in 3.9: arangoimp is just an alias for arangoimp
* remove _arangoimp_ in some future version, and keep _arangoimport_ around

discourage the use of arangoimp

---

3.10/appendix-deprecated.md
3.10/appendix-glossary.md
3.10/http/indexes.md
3.10/indexing-fulltext.md
3.10/indexing-index-basics.md
3.10/indexing-which-index.md
3.10/indexing-working-with-indexes.md
3.10/release-notes-upgrading-changes310.md

arangodb/docs companion PR to arangodb/arangodb PR https://github.com/arangodb/arangodb/pull/15231
Context: https://arangodb.atlassian.net/browse/APM-217

APM-217: deprecate the usage of fulltext indexes

---

3.10/arangosearch-fuzzy-search.md
3.7/arangosearch-fuzzy-search.md
3.8/arangosearch-fuzzy-search.md
3.9/arangosearch-fuzzy-search.md

Hi,
According to [NGRAM_MATCH()](https://www.arangodb.com/docs/3.7/aql/functions-arangosearch.html#ngram_match) and [PHRASE()](https://www.arangodb.com/docs/3.7/aql/functions-arangosearch.html#phrase) documentation, analyzers must have "position" feature in order to work correctly. At the same time "Fuzzy search" branch of documentation has incorrect and misleading examples for [NGRAM_MATCH()](https://www.arangodb.com/docs/stable/arangosearch-fuzzy-search.html#searching-with-ngram_match) and [LEVENSHTEIN_MATCH()](https://www.arangodb.com/docs/stable/arangosearch-fuzzy-search.html#searching-with-levenshtein_match) sections.
This PR proposes a fix.
This has been discussed with the Search team and has their approval.
// Alex.

Fix for analyzer creation function call examples

---

3.10/administration-license.md
3.10/appendix-references-dbobject.md
3.9/administration-license.md
3.9/appendix-references-dbobject.md

Updated license documentation to reflect the final PM decision:
* Time after installation without enforcement (currently 3 days): 1 hour
* Time before license expiration with daily warnings (currently 14 days): 7 days
* Time after expiration switch to Read-Only (currently 14 days): 0 days

license documentation after final pm decision

---

3.9/release-notes-api-changes39.md
3.9/release-notes-upgrading-changes39.md

Docs PR for https://github.com/arangodb/arangodb/pull/15332 and https://github.com/arangodb/arangodb/pull/15333
This PR also moves some other things around in the release note, to potentially better suited locations.

adjust default value for `--rocksdb.max-subcompactions`

---

drivers/java-reference-setup.md

doc for https://github.com/arangodb/arangodb-java-driver/pull/421

Java Driver: added jwt authentication

---

3.10/programs-arangodump-examples.md
3.9/programs-arangodump-examples.md
3.9/release-notes-new-features39.md

Old: 
The number of threads can be controlled via the --threads option, which defaults to 2.
Change to: 
The number of threads can be controlled via the --threads option. The default value changed from 2 to the maximum of 2 and the number of available CPU cores.

Thread default value updated in docs

---

3.10/aql/functions-numeric.md
3.9/aql/functions-numeric.md

* added version number in which functions were introduced
* mention that the functions can return `null` and produce warnings

slightly improve documentation for vector functions

---

3.9/release-notes-new-features39.md
3.9/release-notes-upgrading-changes39.md

Add AF deprecation notice to `release-notes-upgrading-changes39.md` as well, to increase its visibility.
The deprecation notice was previously only in `release-notes-new-features39.md`, where it does not belong IMO.
The PR also contains some other micro changes.

micro improvements

---

3.10/foxx-guides-browser.md
3.4/foxx-guides-browser.md
3.5/foxx-guides-browser.md
3.6/foxx-guides-browser.md
3.7/foxx-guides-browser.md
3.8/foxx-guides-browser.md
3.9/foxx-guides-browser.md

- Add commas to introductory clauses.
- Add oxford comma. [^1]
[^1]: [Strippers, JFK, Stalin, and the Oxford Comma](https://www.verbicidemagazine.com/2011/09/20/strippers-jfk-and-stalin-illustrate-why-you-should-use-the-serial-comma/)

Add commas

---

3.10/programs-arangod-server.md
3.6/programs-arangod-server.md
3.7/programs-arangod-server.md
3.8/programs-arangod-server.md
3.9/programs-arangod-server.md

A customer noted that we have some small inconsistencies between
documentation and implementation. This fixes them.
This is around number of server threads.

Fix small inaccuracies about threads

---

3.10/programs-arangod-encryption.md
_config.yml
_data/3.10-manual.yml

A new startup option section `encryption` was added in 3.10 ([options diff](https://github.com/arangodb/docs/pull/883/files?file-filters%5B%5D=.json&show-viewed-files=true#diff-babd507fbcb16bf83576bf5d21870cc28bb06577521084a74f79ecb4d99bcb4b))
#883 and #878 fail after re-generating 3.10 examples
Text is taken from existing arangodump / arangorestore descriptions.

Add page for --encryption.* startup option category to fix failing builds

---

3.10/http/general.md
3.7/http/general.md
3.8/http/general.md
3.9/http/general.md

1. Unsure if we should state both the actual behavior and the previously documented behavior or just the former ("closes connection, not return NNN" vs. "closes connection")
2. My understanding is that 504 Gateway Timeout isn't currently returned to users and that there's the idea to return 503 in cases where requests can safely be retried and 504 if it's uncertain but that the server currently replies with 503 in all cases while requests may not be retried safely. We should only document the current behavior, therefore adding 503 with a remark about idempotency.
3. Unclear whether Content-Size > 1 GB **and** an actual payload of that size lead to 413 Payload Too Large. Nothing happened in my test, both the client and the server were seemingly idle, no error, no connection closure …

BTS-386 | HTTP Error Handling and Response Codes

---

3.10/analyzers.md
3.10/indexing-geo.md
3.10/indexing-index-basics.md
3.10/indexing-which-index.md
3.7/aql/functions-geo.md
3.7/indexing-geo.md
3.7/indexing-index-basics.md
3.7/indexing-which-index.md
3.8/analyzers.md
3.8/aql/functions-geo.md
3.8/indexing-geo.md
3.8/indexing-index-basics.md
3.8/indexing-which-index.md
3.9/analyzers.md
3.9/aql/functions-geo.md
3.9/indexing-geo.md
3.9/indexing-index-basics.md
3.9/indexing-which-index.md

Backports the majority of changes of #890, keeping statements about the known limitations in 3.9 and older

BTS-459 | GeoJSON docs improvements

---

3.10/programs-arangod-rocksdb.md
3.10/release-notes-api-changes310.md
3.10/release-notes-new-features310.md

Docs PR for https://github.com/arangodb/arangodb/pull/15791
Enable truncate WAL markers in the cluster too. This can speed up truncate operations for large collections/shards.
The newest version of arangosync can now handle truncate markers, so it is safe to activate truncate markers on the arangod side as well.
There is a feature toggle `--rocksdb.use-range-delete-in-wal` to turn off the usage of truncate markers in case of emergency.

optionally use range delete markers in WAL for truncates

---

3.10/installation-linux.md
3.10/installation-mac-osx.md
3.10/installation-windows.md
3.9/installation-linux.md
3.9/installation-mac-osx.md
3.9/installation-windows.md

Initial work on adding verification instructions:

BTS-793 | Add how SHA256 hash of download can be checked

---

drivers/spark-connector-new.md

The schema of a Dataframe being written to an an edge collection must have:
- a non nullable string field named `_from`
- a non nullable string field named `_to`

[DE-190] Spark: edge schema validation

---

_plugins/DocuBlockTag.rb

We use them to describe polymorphic endpoints. Swagger uses paths as attribute keys, which thus needs to be unique:
```json
"paths": {
"/_api/index#persistent": { "post": { ... } },
"/_api/index#ttl": { "post": { ... } },
...
}
```
Fragments allow us to have the same path multiple times, each with a different description for a specific index type, but they are not supposed to be used in requests.
It is easy to remove fragments in the docs generation. In Swagger UI, it is not. The internal data structure follows the spec and uses paths as keys. Therefore, removing fragments early when the spec is loaded is not possible. Removing them late would need to be done in many places, resulting in a very messy workaround. I couldn't make "Try out" requests work so far and Anastasia and I agree that …

BTS-746 | Patch out fragment identifiers in HTTP API endpoints

---

3.10/indexing-index-basics.md
3.10/indexing-ttl.md
3.7/indexing-index-basics.md
3.7/indexing-ttl.md
3.8/indexing-index-basics.md
3.8/indexing-ttl.md
3.9/indexing-index-basics.md
3.9/indexing-ttl.md

Corrects a statement that timestamps would be expected in milliseconds. Found by @solisoft

TTL index expects Unix timestamp in seconds

---

3.10/transactions-transaction-invocation.md
3.7/transactions-transaction-invocation.md
3.8/transactions-transaction-invocation.md
3.9/transactions-transaction-invocation.md

Missing unit reported in #938
Upstream: https://github.com/arangodb/arangodb/pull/16001

Add unit to lockTimeout option (seconds)

---

drivers/spark-connector-new.md

Added option:
- `ignoreNullFields`: whether to ignore null fields during serialization, `false` by default

[DE-210] Spark ignoreNullFields

---

3.10/graphs-pregel.md
3.10/programs-arangod-pregel.md
3.10/release-notes-new-features310.md
3.10/release-notes-upgrading-changes310.md
_data/3.10-manual.yml

docs PR for https://github.com/arangodb/arangodb/pull/16332

add several configuration options for Pregel jobs

---

oasis/getting-started.md

Added a note about creating non-root users in the Getting Started with Oasis.
In the Oasis manual, the [Users](https://www.arangodb.com/docs/stable/oasis/users.html) chapter has no info about creating/managing users in ArangoDB Web Interface. We could refer to [this page](https://www.arangodb.com/docs/3.9/programs-web-interface-users.html) for more details.

Add note about non-root users

---

3.10/tutorials-reduce-memory-footprint.md
3.9/tutorials-reduce-memory-footprint.md

- 3.9.2 lowers the minimum `--cache.size` to 0 to disable it
- 3.10.0 adds optional hash caches for persistent indexes, whose size is also controlled by the startup option

Update Reduce Memory Footprint tutorial

---

3.10/analyzers.md

The classification and nearest_neighbors analyzers only accept supervised models.

Clarify fastText Model Type

---

3.10/data-modeling-collections-collection-methods.md
3.10/data-modeling-collections-database-methods.md
3.10/data-modeling-documents-computed-values.md
3.10/http/document-address-and-etag.md
3.10/programs-arangobackup-examples.md
3.10/programs-arangod-javascript.md
3.10/release-notes-api-changes310.md
3.10/release-notes-new-features310.md
3.10/security-security-options.md
3.10/transactions-transaction-invocation.md
3.8/programs-arangobackup-examples.md
3.8/programs-arangod-javascript.md
3.8/release-notes-new-features38.md
3.8/security-security-options.md
3.8/transactions-transaction-invocation.md
3.9/programs-arangobackup-examples.md
3.9/programs-arangod-javascript.md
3.9/security-security-options.md
3.9/transactions-transaction-invocation.md
drivers/dotnet-usage.md

Also adds a description for `schema` that was missing. I haven't checked if more properties are missing.
The important changes are in this commit: https://github.com/arangodb/docs/pull/1082/commits/a42066dededd681dd32381a822681fbe12336e99

DOC-166 | Add `computedValues` collection property to more JS API pages

---

Dockerfile

Changed base dockerfile image from ubuntu:bionic to ruby:2.6 to avoid ruby build version issues

Dockerfile base image change

---

3.10/programs-arangod-general.md
3.11/programs-arangod-general.md
3.9/programs-arangod-general.md

Documentation for https://arangodb.atlassian.net/browse/BTS-1023:
Refers to:
* devel: https://github.com/arangodb/arangodb/pull/17099
* 3.10: https://github.com/arangodb/arangodb/pull/17098
* 3.9.4: https://github.com/arangodb/arangodb/pull/17109 (3.9.4)

BTS-1023 | `--javascript.copy-installation` fails on some file systems

---

3.10/release-notes-upgrading-changes310.md

Documentation for https://arangodb.atlassian.net/browse/BTS-1032

BTS-1032 | `_rev` not changed when PATCHing document with empty body

---

3.10/appendix-glossary.md
3.10/aql/functions-document.md
3.10/aql/operations-replace.md
3.10/programs-arangoimport-details.md
3.11/appendix-glossary.md
3.11/aql/functions-document.md
3.11/aql/operations-replace.md
3.11/programs-arangoimport-details.md
3.8/appendix-glossary.md
3.8/aql/functions-document.md
3.8/aql/operations-replace.md
3.8/aql/operations-update.md
3.8/programs-arangoimport-details.md
3.9/appendix-glossary.md
3.9/aql/functions-document.md
3.9/aql/operations-replace.md
3.9/aql/operations-update.md
3.9/programs-arangoimport-details.md

Follow up on DOC-215. Updated lead paragraph to avoid ambiguity.

Follow up DOC-215 / Updated lead paragraph

---

3.10/arangosearch-views-search-alias.md
3.10/arangosearch-views.md
3.11/arangosearch-views-search-alias.md
3.11/arangosearch-views.md
3.9/arangosearch-performance.md
3.9/arangosearch-views.md
3.9/release-notes-api-changes39.md
3.9/release-notes-new-features39.md

~~Upstream: https://github.com/arangodb/arangodb/pull/17602 (adds missing `cache` option to storedValues)~~
Too late to include upstream PRs for v3.9.5, added the changes to #1191 for v3.9.6 instead.

Partially revert #1175 because `primarySortCache` will be released in v3.9.6

---

arangograph/cloud-migration-tool.md

Slightly adjusted the step in the workflow about switching applications to use the endpoint of the ArangoGraph deployment.

Migration agent - adjust step about switching endpoint

---

3.9/aql/operations-insert.md
3.9/aql/operations-remove.md
3.9/aql/operations-replace.md
3.9/aql/operations-update.md
3.9/release-notes-api-changes39.md
3.9/release-notes-new-features39.md

Feature PR: https://github.com/arangodb/arangodb/pull/17705
Upstream (DocuBlocks, Metrics, startup options): https://github.com/arangodb/arangodb/pull/17758
(The 3.9.6 release process has already started so we may need to merge this docs PR and leave the upstream PR open for later)
To be forward-ported to 3.10(.2) with minimal changes (introduced in versions). Forward port to 3.11 needs adjustments because the feature also supports persistent indexes with in-memory hash cache and not only the edge cache.

DOC-278 | Edge cache refilling (experimental) [3.9]

---

3.10/aql/extending-conventions.md
3.10/aql/extending-functions.md
3.11/aql/extending-conventions.md
3.11/aql/extending-functions.md
3.8/aql/extending-conventions.md
3.8/aql/extending-functions.md
3.9/aql/extending-conventions.md
3.9/aql/extending-functions.md

V8() is the only remaining function with a JavaScript implementation, living in the default namespace. Native functions don't have a namespace. User-defined functions require one or more namespaces.

DOC-67 | Only built-in JS AQL functions use _aql namespace

---

3.10/deployment-production-checklist.md
3.11/deployment-production-checklist.md
3.8/deployment-production-checklist.md
3.9/deployment-production-checklist.md

The production checklist page doesn't mention explicitly that some OS configuration/tuning should happen.
It links to a page about "Installing on Linux", but not to that page's sub pages. It may not be obvious to users that some configuration changes/tuning are recommend.
Now the sub pages are explicitly mentioned, so that this can't be overlooked.

explicitly mention OS configuration in prod checklist

---

3.10/programs-arangod-env-vars.md
3.11/administration-configuration.md
3.11/programs-arangod-env-vars.md
3.11/release-notes-new-features311.md

Documentation PR for https://github.com/arangodb/arangodb/pull/17977

allow usage of suffix `b` in startup option values

---

styles/site.css

On https://www.arangodb.com/docs/stable/aql/invocation-with-arangosh.html, the example box doesn't visually overlap the ToC but the actual element seems to extend to the right content border. You can see the anchor link floating above the ToC and the ToC cannot be interacted with in the area of the box. This CSS change should fix it. Requires clearing the Cloudflare cache for at least the affected CSS file.

Ensure "On this page" is above example boxes and remove unused, empty CSS file

---

3.10/installation-linux-osconfiguration.md
3.10/installation.md
3.11/installation-linux-osconfiguration.md
3.11/installation.md
3.9/installation-linux-osconfiguration.md

Inspired by https://arangodb.atlassian.net/browse/BTS-1163. 
The requirement for the operating system page size to be <= 4096 was not documented anywhere.
This PR adds it.

add requirement for system page size to documentation

---

3.11/release-notes-api-changes311.md
3.11/release-notes-new-features311.md
3.11/release-notes-upgrading-changes311.md

Created to clarify that there is a requirement that database names, collection names, view names and index names with Unicode characters must be properly NFC-normalized, or they will be rejected by the server.

clarify that unicodes names must be NFC-normalized

---

3.10/http/hot-backup.md
3.11/http/hot-backup.md
3.12/http/hot-backup.md
3.9/http/hot-backup.md

Named graphs are also preserved.
Should we mention anything else?
- Foxx services (but it doesn't include any files they might write to the local file system)
- UDFs
- Analyzers (but not stopword lists that are in the local filesystem)
- ?

From 3.9 on, Hot Backups include View data (not only View definitions)

---

3.11/installation-mac-osx.md
3.11/installation.md
3.12/installation-mac-osx.md
3.12/installation.md

Starting with 3.11, only client tools are provided for macOS.

Installation | macOS client tools only

---

3.10/administration-reduce-memory-footprint.md
3.11/administration-reduce-memory-footprint.md
3.12/administration-reduce-memory-footprint.md

This PR will change the chapter on "Reduce memory footprint" to
give a brief overview over ArangoDB's memory usage and point towards
options to control the behaviour.
Later, we might add links to metrics for RAM usage visibility in that
chapter.

APM-665 - overview of memory usage and options

---

3.10/appendix-deprecated.md
3.11/appendix-deprecated.md
3.12/appendix-deprecated.md
3.12/release-notes-upgrading-changes312.md
3.9/appendix-deprecated.md

Docs PR for https://github.com/arangodb/arangodb/pull/19524/

remove deprecated graph-compatibility functions

---

3.10/install-with-docker.md
3.11/install-with-docker.md
3.12/install-with-docker.md

Relates to https://github.com/arangodb/arangodb-docker/issues/114

Add docker `--platform` note

---

3.10/analyzers.md
3.10/highlights.md
3.10/index.md
3.11/analyzers.md
3.11/highlights.md
3.11/index.md
3.12/analyzers.md
3.12/highlights.md
3.12/index.md

This is a general simplification and also makes the migration to Hugo easier.
Modifies the introduction to ArangoDB inspired by https://github.com/arangodb/arangodb/pull/17986, removing the mention of multi-model and key-value

Always set lead paragraph in front matter

---

3.10/deployment-dc2dc.md
3.11/deployment-dc2dc.md
3.12/deployment-dc2dc.md

There is currently a mix of `datacenter` (majority) vs. `data center` but the Google style guide suggests `data center`.
Shall we address this in this PR?
- When referring to ArangoSync, `Datacenter-to-Datacenter Replication` -> `DataCenter-to-DataCenter-Replication`
- Otherwise `datacenter` -> `data center`

Don't use 1., 2. et cetera in headlines

---

3.11/aql/invocation-with-arangosh.md
3.12/aql/invocation-with-arangosh.md

All other options use `####`, only `allowRetry` used `###`. This changes the latter to the former.

Use the correct heading level for allowRetry

---

3.8/release-notes-api-changes38.md

Set .fixed class for a specific table with very long words
Has no effect in Jekyll toolchain but will have one in Hugo

Add .fixed class to a table
